import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import '../src/speaking-queue.js';
const Q=globalThis.EnglishSpeakingQueue;
const lesson={id:'v2253',title:'Family',curriculum:{mainVocabulary:['niece','spouse','ancestor','descendant','sibling'].map(term=>({term})),extendedVocabulary:[],grammar:[{rule:'稱謂後面加上名字時，兩者都需要大寫。'},{rule:'直接用稱謂代替人名時要大寫。'},{rule:'「誰的＋稱謂」中的稱謂用小寫。'}]}};
const items=Q.inventory(lesson,[],{schemaVersion:'2.25.3'});
const fresh=()=>Q.prepare(Q.reconcile(null,items,{speakingSessionId:'s',lessonId:lesson.id,lessonTitle:lesson.title},'2.25.3'),'a','2.25.3');
function ev(item,index,over={}){
 const example=item.grammarTask==='title_with_name'?'Aunt Mary':item.grammarTask==='title_replacing_name'?'Good morning, Mom.':'my mom';
 const utterance=item.kind==='grammar'?(item.expectedAnswer==='lowercase'?'Lowercase.':'Capital.'):`My ${item.target} lives nearby.`;
 return {coverageId:item.coverageId,sourceVersion:item.sourceVersion,taskMode:item.taskMode,phaseId:'lesson_application',queuePosition:index+1,attemptSequence:index+1,status:'practiced',newPrompt:item.kind==='grammar'?`Capital or lowercase in ${example}?`:`Use ${item.target} in a sentence.`,learnerUtterance:utterance,utteranceReliability:'confirmed',transcriptionIssue:false,learnerFinished:true,modelOnly:false,coachSuppliedAnswer:false,currentItemStateHistory:['PENDING','ACTIVE','AWAITING_LEARNER','RESOLVED'],finalItemState:'RESOLVED',resolution:{hearing:'clear',clarificationPrompt:'',clarificationResponse:'',targetOrTask:'resolved',skipLearnerWords:'',recallSupport:'none',correction:'not_needed',queueUpdated:true},correctionRequired:false,productionQuality:item.kind==='vocabulary'?'acceptable':undefined,grammarRuleId:item.kind==='grammar'?item.coverageId:undefined,grammarTask:item.grammarTask,caseExample:example,accuracy:item.kind==='grammar'?'correct':undefined,needsReview:false,ruleApplication:item.kind==='grammar'?'applied rule':'',newContext:true,notes:'actual evidence',...over};
}
function report(rows=[],over={}){return {type:'SPEAKING_REPORT',schemaVersion:'2.25.3',speakingSessionId:'s',continuationAttemptId:'a',lessonId:lesson.id,completed:false,endReason:'incomplete',stopContext:{externalReason:'',learnerWords:'',clarificationPrompt:'',clarificationResponse:'',coachInitiatedWrapUp:false},speakingMinutes:10,timeBasis:'measured',coverageChecks:rows,speakingCorrections:[],correctionChecks:[],coachExecutionIssues:[],phaseProgress:Q.PHASES.map(phaseId=>({phaseId,status:'partial',notes:'actual '+phaseId})),runtimeQueue:{totalRequiredCoverage:8,resolvedCoverage:rows.length,remainingCoverage:8-rows.length,currentCoverageId:items[rows.length]?.coverageId||null,sessionState:rows.length===8?'FINAL_CHALLENGE':'REQUIRED_PRACTICE'},finalChallenge:{},...over};}
function correction(item,index,resolution='retried') {return {target:item.target,coverageId:item.coverageId,original:'My niece five years old.',better:'My niece is five years old.',reason:'Age needs is.',resolution,learnerRetried:resolution==='retried',retryUtterance:resolution==='retried'?'My niece is five years old.':'',retryLearnerFinished:resolution==='retried',retryUtteranceReliability:resolution==='retried'?'confirmed':'not_applicable',retryTranscriptionIssue:false,learnerDeclineWords:resolution==='declined'?'I do not want to repeat.':''};}

test('V2.25.3 schema and state vocabulary are exposed',()=>{assert(Q.isCurrentItemReport({schemaVersion:'2.25.3'}));assert.deepEqual(Q.TERMINAL_ITEM_STATES,['RESOLVED','RESOLVED_WITH_DECLINED_CORRECTION','EXPLICITLY_SKIPPED']);assert(Q.ITEM_STATES.includes('AWAITING_RETRY'))});
test('1 niece important grammar error remains correction locked',()=>{const e=ev(items[0],0,{learnerUtterance:'My niece five years old.',productionQuality:'needs_review',correctionRequired:true,currentItemStateHistory:['PENDING','ACTIVE','AWAITING_LEARNER','CORRECTION_REQUIRED'],finalItemState:'CORRECTION_REQUIRED',resolution:{hearing:'clear',targetOrTask:'resolved',recallSupport:'none',correction:'unresolved',queueUpdated:false}});const out=Q.applyReport(fresh(),report([e]));assert.equal(out.state.completedCoverage.length,0);assert.equal(out.state.remainingCoverage[0].remainingReason,'correction_unresolved');assert(out.report.coachExecutionIssues.some(x=>x.type==='missing_required_correction'))});
test('2 descendant semantic understanding without target is TARGET_UNRESOLVED',()=>{const rows=items.slice(0,3).map(ev);rows.push(ev(items[3],3,{learnerUtterance:"My niece is my cousin's child.",status:'not_tested',currentItemStateHistory:['PENDING','ACTIVE','AWAITING_LEARNER','TARGET_UNRESOLVED'],finalItemState:'TARGET_UNRESOLVED',resolution:{hearing:'clear',targetOrTask:'unresolved',recallSupport:'natural_followup',correction:'not_needed',queueUpdated:false},remainingReason:'target_not_produced'}));const out=Q.applyReport(fresh(),report(rows));assert.equal(out.state.completedCoverage.length,3);assert.equal(out.state.runtimeQueue.currentCoverageId,items[3].coverageId)});
test('3 prompt tells learner to repeat according to Current Item state',()=>{const source=fs.readFileSync(new URL('../src/speaking-client.js',import.meta.url),'utf8');assert(source.includes('Yes—just one more time. Try it again using [target].'));assert(source.includes('Yes. Try the corrected sentence once.'));assert(!source.includes("No need to repeat the whole thing!"))});
test('4 sibling success reaches RESOLVED and permits queue advancement',()=>{const out=Q.applyReport(fresh(),report(items.slice(0,5).map(ev)));assert.equal(out.state.completedCoverage.length,5);assert.equal(out.state.runtimeQueue.currentCoverageId,items[5].coverageId)});
test('5 and 6 legacy Grammar evidence remains compatible while current Brief removes Grammar coverage prompts',()=>{const source=fs.readFileSync(new URL('../src/speaking-client.js',import.meta.url),'utf8');assert(!source.includes("We haven't practiced the grammar part yet. We still have three grammar items left."));assert(!source.includes('We practiced one grammar rule. We still have two left.'));assert(source.includes('Required Coverage is Vocabulary only'))});
test('7 ambiguous enough plus next does not become learner stop',()=>{const r=report([ev(items[0],0)],{endReason:'learner_requested_stop',stopContext:{learnerWords:'I think enough, we can next.',clarificationPrompt:'',clarificationResponse:'',coachInitiatedWrapUp:false}});const out=Q.applyReport(fresh(),r);assert.equal(out.state.endReason,'incomplete');assert(out.report.validationWarnings.some(x=>x.includes('停止意圖不明確')))});
test('8 unresolved descendant blocks later sibling evidence',()=>{const rows=items.slice(0,3).map(ev);rows.push(ev(items[3],3,{learnerUtterance:'I understand the meaning.',status:'not_tested',currentItemStateHistory:['PENDING','ACTIVE','AWAITING_LEARNER','TARGET_UNRESOLVED'],finalItemState:'TARGET_UNRESOLVED',resolution:{hearing:'clear',targetOrTask:'unresolved',recallSupport:'natural_followup',correction:'not_needed',queueUpdated:false}}));rows.push(ev(items[4],4));const out=Q.applyReport(fresh(),report(rows));assert.equal(out.state.queue[4].state,'NOT_YET_PRACTICED');assert(out.report.coachExecutionIssues.some(x=>x.type==='advanced_before_current_item_resolved'))});
test('9 ancestor awaiting Retry blocks descendant',()=>{const rows=items.slice(0,2).map(ev);rows.push(ev(items[2],2,{productionQuality:'needs_review',correctionRequired:true,currentItemStateHistory:['PENDING','ACTIVE','AWAITING_LEARNER','CORRECTION_REQUIRED','AWAITING_RETRY'],finalItemState:'AWAITING_RETRY',resolution:{hearing:'clear',targetOrTask:'resolved',recallSupport:'none',correction:'unresolved',queueUpdated:false}}));rows.push(ev(items[3],3));const out=Q.applyReport(fresh(),report(rows));assert.equal(out.state.queue[3].state,'NOT_YET_PRACTICED');assert.equal(out.state.runtimeQueue.currentCoverageId,items[2].coverageId)});
test('10 and 11 unasked Grammar is not_tested with no fake attempt sequence',()=>{const out=Q.applyReport(fresh(),report(items.slice(0,5).map(ev)));const grammar=out.report.coverageChecks.filter(x=>x.kind==='grammar');assert.equal(grammar.length,3);assert(grammar.every(x=>x.status==='not_tested'&&x.accuracy==='not_tested'&&x.attemptSequence===null&&x.finalItemState==='PENDING'))});
test('12 remaining Coverage blocks Final Challenge',()=>{const rows=items.slice(0,7).map(ev);const r=report(rows,{completed:true,runtimeQueue:{totalRequiredCoverage:8,resolvedCoverage:7,remainingCoverage:1,currentCoverageId:items[7].coverageId,sessionState:'REQUIRED_PRACTICE'},finalChallenge:{attemptSequence:20,newPrompt:'Final',learnerUtterance:'My sibling visits Aunt Mary.',utteranceReliability:'confirmed',transcriptionIssue:false,learnerFinished:true,independentProduction:true,coachSuppliedAnswer:false,feedbackGiven:true,preFinalAuditPassed:true,remainingCoverageBeforeChallenge:1,auditedCoverageIds:items.map(x=>x.coverageId)}});const out=Q.applyReport(fresh(),r);assert.equal(out.state.completed,false);assert.equal(out.state.finalChallengeStatus,null)});
test('resolved correction requires full Correction Lock history and Retry',()=>{const e=ev(items[0],0,{learnerUtterance:'My niece five years old.',productionQuality:'needs_review',correctionRequired:true,currentItemStateHistory:['PENDING','ACTIVE','AWAITING_LEARNER','CORRECTION_REQUIRED','AWAITING_RETRY','RESOLVED'],finalItemState:'RESOLVED',resolution:{hearing:'clear',targetOrTask:'resolved',recallSupport:'none',correction:'retried',queueUpdated:true}});const r=report([e]);r.speakingCorrections=[correction(items[0],0)];const out=Q.applyReport(fresh(),r);assert.equal(out.state.completedCoverage.length,1)});
test('full queue plus authoritative runtime audit permits Final Challenge',()=>{const rows=items.map(ev);const r=report(rows,{completed:true,runtimeQueue:{totalRequiredCoverage:8,resolvedCoverage:8,remainingCoverage:0,currentCoverageId:null,sessionState:'FINAL_CHALLENGE'},finalChallenge:{attemptSequence:20,newPrompt:'Use two targets.',learnerUtterance:'My sibling visits my niece.',utteranceReliability:'confirmed',transcriptionIssue:false,learnerFinished:true,independentProduction:true,coachSuppliedAnswer:false,feedbackGiven:true,preFinalAuditPassed:true,remainingCoverageBeforeChallenge:0,auditedCoverageIds:items.map(x=>x.coverageId)}});assert.equal(Q.applyReport(fresh(),r).state.completed,true)});
