import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import '../src/speaking-queue.js';
const Q=globalThis.EnglishSpeakingQueue;
const V=Q.SCHEMA_VERSION;
const lesson={id:'v2254',title:'Family',curriculum:{mainVocabulary:['niece','ancestor','descendant','sibling','spouse'].map(term=>({term})),extendedVocabulary:[],grammar:[{rule:'稱謂後面加上名字時，兩者都需要大寫。'},{rule:'直接用稱謂代替人名時要大寫。'},{rule:'「誰的＋稱謂」中的稱謂用小寫。'}]}};
const items=Q.inventory(lesson,[],{schemaVersion:V});
const fresh=()=>Q.prepare(Q.reconcile(null,items,{speakingSessionId:'s254',lessonId:lesson.id,lessonTitle:lesson.title},V),'a254',V);
function ev(item,index,over={}){
 const example=item.grammarTask==='title_with_name'?'Aunt Mary':item.grammarTask==='title_replacing_name'?'Mom, can you help me?':'my mom';
 const utterance=item.kind==='grammar'?(item.expectedAnswer==='lowercase'?'Lowercase.':'Capital.'):`My ${item.target} lives nearby.`;
 return {coverageId:item.coverageId,sourceVersion:item.sourceVersion,taskMode:item.taskMode,phaseId:'lesson_application',queuePosition:index+1,attemptSequence:index+1,status:'practiced',newPrompt:item.kind==='grammar'?`Capital or lowercase in ${example}?`:`Use ${item.target} in a sentence.`,learnerUtterance:utterance,utteranceReliability:'confirmed',transcriptionIssue:false,semanticGuessUsed:false,learnerFinished:true,modelOnly:false,coachSuppliedAnswer:false,independentAfterCoachAnswer:false,currentItemStateHistory:['PENDING','ACTIVE','AWAITING_LEARNER','RESOLVED'],runtimeFinalState:'RESOLVED',evidenceValid:true,correctionLock:'none',resolution:{hearing:'clear',clarificationPrompt:'',clarificationResponse:'',targetOrTask:'resolved',skipLearnerWords:'',recallSupport:'none',correction:'not_needed',queueUpdated:true},correctionRequired:false,productionQuality:item.kind==='vocabulary'?'acceptable':undefined,grammarRuleId:item.kind==='grammar'?item.coverageId:undefined,grammarTask:item.grammarTask,caseExample:example,accuracy:item.kind==='grammar'?'correct':null,needsReview:false,ruleApplication:item.kind==='grammar'?'applied rule':'',newContext:true,praiseGiven:false,notes:'actual evidence',...over};
}
function report(rows=[],over={}){return {type:'SPEAKING_REPORT',schemaVersion:V,speakingSessionId:'s254',continuationAttemptId:'a254',lessonId:lesson.id,completed:false,endReason:'incomplete',stopContext:{externalReason:'',learnerWords:'',clarificationPrompt:'',clarificationResponse:'',coachInitiatedWrapUp:false},speakingMinutes:10,timeBasis:'measured',coverageChecks:rows,speakingCorrections:[],correctionChecks:[],coachExecutionIssues:[],phaseProgress:Q.PHASES.map(phaseId=>({phaseId,status:'partial',notes:'actual '+phaseId})),runtimeQueue:{totalRequiredCoverage:8,resolvedCoverage:rows.length,remainingCoverage:8-rows.length,currentCoverageId:items[rows.length]?.coverageId||null,currentRequiredItem:items[rows.length]?.coverageId||null,correctionLockCount:0,allEvidenceValid:false,sessionState:rows.length===8?'FINAL_CHALLENGE':'REQUIRED_PRACTICE'},finalChallenge:{attemptSequence:null,newPrompt:'',learnerUtterance:'',utteranceReliability:'not_applicable',transcriptionIssue:false,learnerFinished:false,independentProduction:false,coachSuppliedAnswer:false,feedbackGiven:false,correction:'not_needed',correctionResolved:false,preFinalAuditPassed:false,finalAuditPassed:false,remainingCoverageBeforeChallenge:null,auditedCoverageIds:[],evidenceValid:false},...over};}
function retryCorrection(item,original,better,resolution='retried'){return {target:item.target,coverageId:item.coverageId,original,better,reason:'Important language correction.',resolution,learnerRetried:resolution==='retried',retryUtterance:resolution==='retried'?better:'',retryLearnerFinished:resolution==='retried',retryUtteranceReliability:resolution==='retried'?'confirmed':'not_applicable',retryTranscriptionIssue:false,learnerDeclineWords:resolution==='declined'?"I understand, but I don't want to repeat it.":''};}
function locked(item,index,utterance){return ev(item,index,{learnerUtterance:utterance,productionQuality:'needs_review',needsReview:true,correctionRequired:true,currentItemStateHistory:['PENDING','ACTIVE','AWAITING_LEARNER','CORRECTION_REQUIRED','AWAITING_RETRY'],runtimeFinalState:'AWAITING_RETRY',evidenceValid:false,correctionLock:'awaiting_retry',resolution:{hearing:'clear',targetOrTask:'resolved',recallSupport:'none',correction:'unresolved',queueUpdated:false}});}

test('V2.25.4 is the single runtime schema and includes required states',()=>{assert.equal(V,'2.25.4');assert(Q.isRuntimeIntegrityReport({schemaVersion:V}));for(const x of ['TASK_UNRESOLVED','SESSION_STOPPED'])assert(Q.ITEM_STATES.includes(x));});
test('01 niece target production remains locked until correction Retry',()=>{const out=Q.applyReport(fresh(),report([locked(items[0],0,'Yes, I have a niece, and my niece five years old.')]));assert.equal(out.state.completedCoverage.length,0);assert.equal(out.state.queue[0].correctionLock,'awaiting_retry');assert.equal(out.state.runtimeQueue.currentCoverageId,items[0].coverageId);});
test('02 ancestor tense error blocks descendant until Retry',()=>{const rows=[ev(items[0],0),locked(items[1],1,'My ancestor was a businessman and he is sell pork in the market.')];const out=Q.applyReport(fresh(),report(rows));assert.equal(out.state.completedCoverage.length,1);assert.equal(out.state.runtimeQueue.currentCoverageId,items[1].coverageId);});
test('03 descendant identical proposed correction is retracted',()=>{const row=ev(items[0],0,{learnerUtterance:'My niece is a descendant of my cousin.',productionQuality:'needs_review',needsReview:true,correctionRequired:true,currentItemStateHistory:['PENDING','ACTIVE','AWAITING_LEARNER','CORRECTION_REQUIRED','RESOLVED'],runtimeFinalState:'RESOLVED',evidenceValid:true,resolution:{hearing:'clear',targetOrTask:'resolved',recallSupport:'none',correction:'retried',queueUpdated:true}});const r=report([row]);r.speakingCorrections=[retryCorrection(items[0],row.learnerUtterance,row.learnerUtterance)];const out=Q.applyReport(fresh(),r);assert.equal(out.report.speakingCorrections.length,0);assert(out.report.coachExecutionIssues.some(x=>x.type==='false_correction'));assert.equal(out.state.completedCoverage.length,1);});
test('04 suspicious ASR with semantic guessing remains hearing locked',()=>{const row=ev(items[0],0,{learnerUtterance:'He is very head boy.',utteranceReliability:'uncertain',transcriptionIssue:true,semanticGuessUsed:true,status:'not_tested',currentItemStateHistory:['PENDING','ACTIVE','AWAITING_LEARNER','HEARING_UNRESOLVED'],runtimeFinalState:'HEARING_UNRESOLVED',evidenceValid:false,correctionLock:'none',resolution:{hearing:'unresolved',targetOrTask:'unresolved',recallSupport:'none',correction:'not_needed',queueUpdated:false}});const out=Q.applyReport(fresh(),report([row]));assert.equal(out.state.completedCoverage.length,0);assert(out.report.coachExecutionIssues.some(x=>x.type==='semantic_guess_under_uncertainty'));});
test('05 spouse pending blocks Grammar even after Next',()=>{const rows=items.slice(0,4).map(ev);rows.push(ev(items[5],5));const out=Q.applyReport(fresh(),report(rows));assert.equal(out.state.runtimeQueue.currentCoverageId,items[4].coverageId);assert.equal(out.state.queue[5].state,'NOT_YET_PRACTICED');});
test('06 spouse language error cannot be closed by praise',()=>{const rows=items.slice(0,4).map(ev);rows.push(locked(items[4],4,'If I can marry my spouse, will be my partner.'));rows[4].praiseGiven=true;const out=Q.applyReport(fresh(),report(rows));assert(out.report.coachExecutionIssues.some(x=>x.type==='unsupported_praise'));assert.equal(out.state.runtimeQueue.currentCoverageId,items[4].coverageId);});
test('07 Grammar ASR failure stays HEARING_UNRESOLVED',()=>{const rows=items.slice(0,5).map(ev);rows.push(ev(items[5],5,{learnerUtterance:"I didn't protest.",utteranceReliability:'uncertain',transcriptionIssue:true,status:'not_tested',accuracy:'not_tested',currentItemStateHistory:['PENDING','ACTIVE','AWAITING_LEARNER','HEARING_UNRESOLVED'],runtimeFinalState:'HEARING_UNRESOLVED',evidenceValid:false,correctionLock:'none',resolution:{hearing:'unresolved',targetOrTask:'unresolved',recallSupport:'none',correction:'not_needed',queueUpdated:false}}));const out=Q.applyReport(fresh(),report(rows));assert.equal(out.state.queue[5].state,'NOT_YET_PRACTICED');assert.equal(out.report.coverageChecks.find(x=>x.coverageId===items[5].coverageId).accuracy,'not_tested');});
test('08 Coach supplied Grammar answer without independent response is not evidence',()=>{const rows=items.slice(0,5).map(ev);rows.push(ev(items[5],5,{learnerUtterance:'Okay.',coachSuppliedAnswer:true,independentAfterCoachAnswer:false,status:'not_tested',accuracy:'incorrect',currentItemStateHistory:['PENDING','ACTIVE','AWAITING_LEARNER','TASK_UNRESOLVED'],runtimeFinalState:'TASK_UNRESOLVED',evidenceValid:false,correctionLock:'none',resolution:{hearing:'clear',targetOrTask:'unresolved',recallSupport:'coach_answer',correction:'not_needed',queueUpdated:false}}));const out=Q.applyReport(fresh(),report(rows));const check=out.report.coverageChecks.find(x=>x.coverageId===items[5].coverageId);assert.equal(check.status,'not_tested');assert.equal(check.accuracy,'not_tested');});
test('09 possessive Grammar resolves independently',()=>{const rows=items.slice(0,7).map(ev);rows.push(ev(items[7],7));const out=Q.applyReport(fresh(),report(rows));assert.equal(out.state.completedCoverage.length,8);assert.equal(out.state.queue[7].evidence.accuracy,'correct');});
test('10 completion prompt rule requires full queue and correction audit',()=>{const source=fs.readFileSync(new URL('../src/speaking-client.js',import.meta.url),'utf8');assert(source.includes('fullQueueAudit()'));assert(source.includes('correctionLockCount'));});
test('11 correctionLockCount blocks Final Challenge',()=>{const rows=items.map(ev);const r=report(rows,{completed:true,runtimeQueue:{totalRequiredCoverage:8,resolvedCoverage:8,remainingCoverage:0,currentCoverageId:null,currentRequiredItem:null,correctionLockCount:1,allEvidenceValid:false,sessionState:'REQUIRED_PRACTICE'},finalChallenge:{attemptSequence:20,newPrompt:'Final',learnerUtterance:'My sibling visits my niece.',utteranceReliability:'confirmed',transcriptionIssue:false,learnerFinished:true,independentProduction:true,coachSuppliedAnswer:false,feedbackGiven:true,correction:'not_needed',correctionResolved:true,preFinalAuditPassed:true,finalAuditPassed:true,remainingCoverageBeforeChallenge:0,auditedCoverageIds:items.map(x=>x.coverageId),evidenceValid:true}});assert.equal(Q.applyReport(fresh(),r).state.completed,false);});
test('12 unfinished pause does not satisfy learner completion',()=>{const row=ev(items[0],0,{learnerUtterance:'My ancestor was... um... and...',learnerFinished:false,status:'not_tested',currentItemStateHistory:['PENDING','ACTIVE','AWAITING_LEARNER','TARGET_UNRESOLVED'],runtimeFinalState:'TARGET_UNRESOLVED',evidenceValid:false,correctionLock:'none',resolution:{hearing:'clear',targetOrTask:'unresolved',recallSupport:'none',correction:'not_needed',queueUpdated:false}});assert.equal(Q.applyReport(fresh(),report([row])).state.completedCoverage.length,0);});
test('13 explicit correction decline resolves with needs_review',()=>{const row=locked(items[0],0,'My niece five years old.');Object.assign(row,{currentItemStateHistory:['PENDING','ACTIVE','AWAITING_LEARNER','CORRECTION_REQUIRED','AWAITING_RETRY','RESOLVED_WITH_DECLINED_CORRECTION'],runtimeFinalState:'RESOLVED_WITH_DECLINED_CORRECTION',evidenceValid:true,correctionLock:'declined',resolution:{hearing:'clear',targetOrTask:'resolved',recallSupport:'none',correction:'declined',queueUpdated:true}});const r=report([row]);r.speakingCorrections=[retryCorrection(items[0],row.learnerUtterance,'My niece is five years old.','declined')];const out=Q.applyReport(fresh(),r);assert.equal(out.state.completedCoverage.length,1);assert.equal(out.state.queue[0].evidence.needsReview,true);});
test('14 false coach correction creates no learner weakness',()=>{const row=ev(items[0],0);const r=report([row]);r.speakingCorrections=[retryCorrection(items[0],row.learnerUtterance,row.learnerUtterance)];const out=Q.applyReport(fresh(),r);assert.equal(out.report.speakingCorrections.length,0);assert.equal(out.report.grammarToReview?.length||0,0);});
test('15 Next cannot skip AWAITING_RETRY',()=>{const rows=[locked(items[0],0,'My niece five years old.'),ev(items[1],1)];const out=Q.applyReport(fresh(),report(rows));assert.equal(out.state.completedCoverage.length,0);assert.equal(out.state.runtimeQueue.currentCoverageId,items[0].coverageId);});
test('16 explicit skip advances conversation but never completes coverage',()=>{const row=ev(items[0],0,{status:'not_tested',learnerUtterance:'Skip this word.',currentItemStateHistory:['PENDING','ACTIVE','AWAITING_LEARNER','EXPLICITLY_SKIPPED'],runtimeFinalState:'EXPLICITLY_SKIPPED',evidenceValid:false,correctionLock:'none',resolution:{hearing:'clear',targetOrTask:'explicit_skip',skipLearnerWords:'Skip this word.',recallSupport:'none',correction:'not_needed',queueUpdated:true}});const out=Q.applyReport(fresh(),report([row],{completed:true}));assert.equal(out.state.completed,false);assert.equal(out.state.queue[0].state,'NOT_YET_PRACTICED');});
test('17 Coach answer Vocabulary requires later independent target production',()=>{const row=ev(items[0],0,{learnerUtterance:'A child in my family.',coachSuppliedAnswer:true,independentAfterCoachAnswer:false,status:'not_tested',currentItemStateHistory:['PENDING','ACTIVE','AWAITING_LEARNER','TARGET_UNRESOLVED'],runtimeFinalState:'TARGET_UNRESOLVED',evidenceValid:false,correctionLock:'none',resolution:{hearing:'clear',targetOrTask:'unresolved',recallSupport:'coach_answer',correction:'not_needed',queueUpdated:false}});assert.equal(Q.applyReport(fresh(),report([row])).state.completedCoverage.length,0);});
test('18 all Required Coverage without Final Challenge remains incomplete with null semantics',()=>{const out=Q.applyReport(fresh(),report(items.map(ev),{completed:true,runtimeQueue:{totalRequiredCoverage:8,resolvedCoverage:8,remainingCoverage:0,currentCoverageId:null,currentRequiredItem:null,correctionLockCount:0,allEvidenceValid:true,sessionState:'FINAL_CHALLENGE'}}));assert.equal(out.state.completed,false);assert.equal(out.report.finalChallenge.attemptSequence,null);assert.equal(out.report.finalChallenge.remainingCoverageBeforeChallenge,null);assert.equal(out.report.finalChallenge.finalAuditPassed,false);});
