import test from 'node:test';
import assert from 'node:assert/strict';
import '../src/speaking-queue.js';
import { createSpeakingService } from '../src/speaking-service.mjs';
import { sourceContext } from '../src/source-context.mjs';
const Q = globalThis.EnglishSpeakingQueue;
const copy = x => structuredClone(x);
const lesson = {id:'fixture',title:'Family',curriculum:{mainVocabulary:['niece','spouse','ancestor','descendant','sibling'].map(term=>({term,meaning:term})),extendedVocabulary:[],grammar:[{rule:'稱謂後面加上名字時，兩者都需要大寫。'},{rule:'直接用稱謂代替人名時要大寫。'},{rule:'「誰的＋稱謂」中的稱謂用小寫。'}]}};
const corrections = ['spouse','descendant','sibling','niece','ancestor','sibling','descendant'].map((target,i)=>({lessonId:lesson.id,correctionId:'c'+i,target,component:'Vocabulary',round:i<4?'production':'spelling',prompt:'Use '+target,originalAnswer:'original '+i,gptSuggestedAnswer:'better '+i,learnerCorrection:'learner '+i}));
const items = Q.inventory(lesson,corrections,{schemaVersion:'2.25.1'});
const legacyItems = Q.inventory(lesson,corrections,{schemaVersion:'2.24.0'});
const fresh = () => Q.prepare(Q.reconcile(null,items,{speakingSessionId:'logical-1',lessonId:lesson.id,lessonTitle:lesson.title},'2.25.0'),'attempt-1','2.25.0');
function evidence(item,index,overrides={}) {
  const example=item.grammarTask==='title_with_name'?'Aunt Mary':item.grammarTask==='title_replacing_name'?'Good morning, Mom.':'my mom';
  const utterance=item.kind==='grammar'?(item.expectedAnswer==='lowercase'?'Lowercase.':'Capital.'):'My '+item.target+' five years old.';
  return {coverageId:item.coverageId,sourceVersion:item.sourceVersion,taskMode:item.taskMode,phaseId:'lesson_application',sequence:index+1,status:'practiced',newPrompt:item.kind==='grammar'?'Capital or lowercase in '+example+'?':'Tell me something using '+item.target+'.',learnerUtterance:utterance,utteranceReliability:'confirmed',transcriptionIssue:false,learnerFinished:true,modelOnly:false,coachSuppliedAnswer:false,productionQuality:item.kind==='vocabulary'?'needs_review':undefined,newContext:true,grammarRuleId:item.coverageId,grammarTask:item.grammarTask,caseExample:example,ruleApplication:item.kind==='grammar'?'applied rule':'',notes:'Actual learner attempt',...overrides};
}
function report(count=8) {
  return {type:'SPEAKING_REPORT',schemaVersion:'2.25.1',speakingSessionId:'logical-1',continuationAttemptId:'attempt-1',lessonId:lesson.id,completed:true,endReason:'completed',speakingMinutes:25,timeBasis:'measured',coverageChecks:items.slice(0,count).map(evidence),speakingCorrections:[],correctionChecks:[],phaseProgress:Q.PHASES.map(phaseId=>({phaseId,status:'completed',notes:'actual '+phaseId})),finalChallenge:{sequence:50,newPrompt:'Introduce two family members in two sentences.',learnerUtterance:'My sibling visited my niece. We had dinner.',utteranceReliability:'confirmed',transcriptionIssue:false,learnerFinished:true,independentProduction:true,coachSuppliedAnswer:false,feedbackGiven:true}};
}

test('Required inventory is exactly 5 Vocabulary + 3 Grammar; corrections and spelling are context only',()=>{assert.equal(items.length,8);assert.equal(items.filter(x=>x.kind==='vocabulary').length,5);assert.equal(items.filter(x=>x.kind==='grammar').length,3);assert(!items.some(x=>['correction_transfer','spelling_recall'].includes(x.taskMode)))});
test('V2.24 legacy inventory retains 15 queue items for old Reports',()=>{assert.equal(legacyItems.length,15);assert.equal(legacyItems.filter(x=>x.taskMode==='spelling_recall').length,3);assert.equal(legacyItems.filter(x=>x.taskMode==='correction_transfer').length,4)});
test('A: Vocabulary target used in an incorrect sentence is practiced and correction is saved',()=>{const r=report();r.coverageChecks[0]=evidence(items[0],0,{learnerUtterance:'My niece five years old.',productionQuality:'needs_review'});r.speakingCorrections=[{target:'niece',coverageId:items[0].coverageId,original:'My niece five years old.',better:'My niece is five years old.',reason:'Add the verb is.',learnerRetried:true,retryUtterance:'My niece is five years old.'}];const out=Q.applyReport(fresh(),r);assert.equal(out.state.queue[0].state,'PRACTICED');assert.equal(out.report.coverageChecks[0].productionQuality,'needs_review');assert.equal(out.report.speakingCorrections[0].better,'My niece is five years old.')});
test('B: Vocabulary prompt mentions target but learner does not produce it',()=>{const r=report();r.coverageChecks[4]=evidence(items[4],4,{learnerUtterance:'I have a sister. We talk every day.'});const s=Q.applyReport(fresh(),r).state;assert.equal(s.remainingCoverage.length,1);assert.equal(s.remainingCoverage[0].target,'sibling');assert.equal(s.remainingCoverage[0].remainingReason,'coach_only_target')});
test('G: Warm-up spontaneous target can satisfy Vocabulary Coverage with reliable evidence',()=>{const item=items.find(x=>x.target==='niece');const a=Q.assess(item,evidence(item,0,{phaseId:'warmup',newPrompt:'Who do you spend time with in your family?',learnerUtterance:'I spend a lot of time with my niece.'}));assert.equal(a.ok,true)});
test('Warm-up does not bypass Grammar task evidence rules',()=>{const item=items.find(x=>x.kind==='grammar');const a=Q.assess(item,evidence(item,0,{phaseId:'warmup'}));assert.equal(a.ok,false);assert.equal(a.remainingReason,'wrong_task_mode')});
test('C: Wrong Grammar answer counts as practiced and stays inaccurate',()=>{const grammar=items.find(x=>x.grammarTask==='title_with_name');const a=Q.assess(grammar,evidence(grammar,6,{learnerUtterance:'Lowercase.'}));assert(a.ok);assert.equal(a.accuracy,'incorrect');assert.equal(a.needsReview,true)});
test('D: Okay is not a Grammar answer',()=>{const grammar=items.find(x=>x.grammarTask==='possessive_title');const a=Q.assess(grammar,evidence(grammar,7,{learnerUtterance:'Okay.'}));assert.equal(a.ok,false);assert.equal(a.remainingReason,'no_learner_response')});
test('E: Untested previous production corrections do not block completion',()=>{const out=Q.applyReport(fresh(),report());assert.equal(out.state.completed,true);assert.equal(out.state.sessionCoverage.total,8);assert.equal(out.report.correctionChecks.length,0)});
test('F: Previous spelling corrections do not block completion',()=>{const out=Q.applyReport(fresh(),report());assert.equal(out.state.completed,true);assert(!out.state.queue.some(x=>x.taskMode==='spelling_recall'))});
test('G: Speaking correction requires complete My sentence / Better / Why data and Retry evidence',()=>{const r=report();r.speakingCorrections=[{target:'niece',original:'She is happiness girl.',better:'She is a happy girl.',reason:'Use the adjective happy.',learnerRetried:true,retryUtterance:'She is a happy girl.'}];const out=Q.applyReport(fresh(),r);assert.equal(out.report.speakingCorrections[0].learnerRetried,true);assert.throws(()=>{const bad=report();bad.speakingCorrections=[{original:'x',better:'y',reason:'z',learnerRetried:true}];Q.applyReport(fresh(),bad)},/retryUtterance/)});
test('H: 4/5 Vocabulary + 2/3 Grammar continuation has exactly 2 remaining',()=>{const chosen=[...items.filter(x=>x.kind==='vocabulary').slice(0,4),...items.filter(x=>x.kind==='grammar').slice(0,2)];const r=report();r.coverageChecks=chosen.map((x,i)=>evidence(x,i));r.completed=false;r.finalChallenge={};const first=Q.applyReport(fresh(),r).state;const next=Q.prepare(first,'attempt-2','2.25.0');assert.equal(next.completedCoverage.length,6);assert.equal(next.remainingCoverage.length,2);assert.equal(next.activeAttempt.items.length,2);assert.equal(next.speakingSessionId,'logical-1')});
test('Coverage and quality stay separate; no mastery field is created',()=>{const out=Q.applyReport(fresh(),report());assert.equal(out.state.completedCoverage.length,8);assert(!Object.hasOwn(out.state,'mastery'));assert(out.report.coverageChecks.filter(x=>x.kind==='vocabulary').every(x=>x.productionQuality==='needs_review'))});
test('Explicit Grammar choice is required; transcript capitalization alone is not evidence',()=>{const grammar=items.find(x=>x.kind==='grammar');const a=Q.assess(grammar,evidence(grammar,6,{learnerUtterance:'Aunt Mary visits us.'}));assert.equal(a.ok,false)});
test('Unreliable transcript does not count',()=>{const r=report();r.coverageChecks[0].utteranceReliability='uncertain';r.coverageChecks[0].transcriptionIssue=true;const s=Q.applyReport(fresh(),r).state;assert.equal(s.remainingCoverage.length,1);assert.equal(s.remainingCoverage[0].remainingReason,'unreliable_transcript')});
test('Model-only response and unfinished formulation do not count',()=>{const model=evidence(items[0],0,{modelOnly:true});assert.equal(Q.assess(items[0],model).ok,false);const open=evidence(items[0],0,{learnerFinished:false});assert.equal(Q.assess(items[0],open).ok,false)});
test('H: A pause during formulation stays unfinished and does not count',()=>{const item=items.find(x=>x.target==='niece');const a=Q.assess(item,evidence(item,0,{learnerUtterance:'My niece is... um...',learnerFinished:false}));assert.equal(a.ok,false);assert.equal(a.remainingReason,'no_learner_response')});
test('Final Challenge cannot supply missing Required Coverage',()=>{const r=report();r.coverageChecks[0].phaseId='final_challenge';assert.equal(Q.applyReport(fresh(),r).state.completed,false)});
test('Final Challenge must occur after the accepted Coverage',()=>{const r=report();r.finalChallenge.sequence=7;assert.equal(Q.applyReport(fresh(),r).state.completed,false)});
test('V2.25 completion requires Coverage + learnerFinished + feedback, without adding correction gates',()=>{const r=report();r.phaseProgress[2].status='partial';assert.equal(Q.applyReport(fresh(),r).state.completed,true);const missing=report();missing.finalChallenge.feedbackGiven=false;assert.equal(Q.applyReport(fresh(),missing).state.completed,false)});
test('Coach wrap-up plus Yeah is not valid learner agreement',()=>{const r=report(4);r.completed=false;r.endReason='learner_agreed_stop';r.stopContext={externalReason:'long conversation',learnerWords:'Yeah.',coachInitiatedWrapUp:true};r.finalChallenge={};const s=Q.applyReport(fresh(),r).state;assert.equal(s.endReason,'incomplete');assert.equal(s.completedCoverage.length,4)});
test('Explicit learner stop keeps valid partial evidence',()=>{const r=report(4);r.completed=false;r.endReason='learner_requested_stop';r.stopContext={learnerWords:'I need to stop now.'};r.finalChallenge={};assert.equal(Q.applyReport(fresh(),r).state.endReason,'learner_requested_stop')});
test('Same attempt import is idempotent and conflicting payload is rejected',()=>{const r=report(4),a=Q.applyReport(fresh(),r).state,b=Q.applyReport(a,r);assert.equal(b.duplicate,true);assert.equal(b.state.attempts.length,1);r.speakingMinutes=99;assert.throws(()=>Q.applyReport(a,r),/不同回報/)});
test('Changed required source invalidates only that evidence and Final Challenge',()=>{const s=Q.applyReport(fresh(),report()).state;const next=copy(items);next[0].sourceVersion='new';const b=Q.reconcile(s,next,{},'2.25.0');assert.equal(b.completedCoverage.length,7);assert.equal(b.finalChallengeStatus,null);assert.equal(b.completed,false)});
test('Removing legacy correction/spelling queue during upgrade preserves matching Vocabulary/Grammar evidence',()=>{const legacyFresh=Q.prepare(Q.reconcile(null,legacyItems,{speakingSessionId:'old',lessonId:lesson.id,lessonTitle:lesson.title},'2.24.0'),'old-attempt','2.24.0');legacyFresh.queue.slice(0,8).forEach(x=>x.state='PRACTICED_RELIABLY');const upgraded=Q.reconcile(legacyFresh,items,{},'2.25.0');assert.equal(upgraded.queue.length,8);assert.equal(upgraded.completedCoverage.length,8)});
test('Schema classes cannot be mixed inside one prepared attempt',()=>{assert.throws(()=>Q.applyReport(fresh(),{...report(),schemaVersion:'2.24.0'}),/schemaVersion/)});
test('No time limit; 90 minutes retained and unknown time stays null',()=>{const r=report();r.speakingMinutes=90;assert.equal(Q.applyReport(fresh(),r).report.speakingMinutes,90);const u=report();u.timeBasis='not_recorded';u.speakingMinutes=null;assert.equal(Q.applyReport(fresh(),u).report.speakingMinutes,null)});
test('2.24, 2.25.0 and 2.25.1 Reports remain compatible; 2.25+ is simplified',()=>{assert(Q.isQueueReport({schemaVersion:'2.24.0'}));assert(Q.isQueueReport({schemaVersion:'2.25.0'}));assert(Q.isQueueReport({schemaVersion:'2.25.1'}));assert(!Q.isSimplifiedReport({schemaVersion:'2.24.0'}));assert(Q.isSimplifiedReport({schemaVersion:'2.25.0'}));assert(Q.isSimplifiedReport({schemaVersion:'2.25.1'}))});

const session={id:'written',lessonId:lesson.id,lessonTitle:lesson.title,answers:corrections.map((x,i)=>({id:'q'+i,component:x.component,round:x.round,target:x.target,prompt:x.prompt,userAnswer:x.originalAnswer,status:'answered'}))};
const grades={sessionId:session.id,importedAt:'2026-09-17',gradedAnswers:corrections.map((x,i)=>({id:'q'+i,status:'incorrect',better:x.gptSuggestedAnswer,corrected:true,correctionAnswer:x.learnerCorrection}))};
function memoryStore(){let db=new Map(),source={'english_os_lessons':JSON.stringify([lesson]),'english_os_sessions':JSON.stringify([session]),'english_os_gpt_reports':JSON.stringify([grades])};return {source:async()=>copy(source),get:async id=>copy(db.get(id)||null),latest:async id=>copy([...db.values()].filter(x=>x.lesson_id===id).at(-1)||null),save:async(s,r)=>{const prev=db.get(s.speakingSessionId);if(r===null?!!prev:prev?.revision!==r)return false;if(r===null&&[...db.values()].some(x=>x.lesson_id===s.lessonId&&!x.state.completed))return false;db.set(s.speakingSessionId,{lesson_id:s.lessonId,state:copy(s),revision:(r||0)+1});return true},changeSource:fn=>fn(source),rows:()=>copy([...db.values()])}}
async function serverFixture(){const store=memoryStore();let id=0;const api=createSpeakingService(store,()=>String(++id));const ctx=sourceContext(await store.source(),lesson.id);const inv=Q.inventory(ctx.lesson,ctx.corrections,{schemaVersion:'2.25.1'});const prepared=await api({action:'prepare',schemaVersion:'2.25.1',lessonId:lesson.id,sourceFingerprint:Q.version(inv)});return {store,api,inv,prepared}}
function serverReport(f,count=8){const r=report(count);r.speakingSessionId=f.prepared.state.speakingSessionId;r.continuationAttemptId=f.prepared.state.activeAttempt.id;r.coverageChecks=f.inv.slice(0,count).map(evidence);return r}
test('Server rebuilds only 8 Required items from stored sources and ignores caller queue',async()=>{const f=await serverFixture();assert.equal(f.inv.length,8);const result=await f.api({action:'report',lessonId:lesson.id,report:serverReport(f,6),queue:[]});assert.equal(result.state.completedCoverage.length,6);assert.equal(result.state.remainingCoverage.length,2);assert.equal(f.store.rows()[0].state.attempts.length,1)});
test('Server preserves the V2.25.1 patch schema in Session and attempt',async()=>{const f=await serverFixture();assert.equal(f.prepared.state.schemaVersion,'2.25.1');assert.equal(f.prepared.state.activeAttempt.schemaVersion,'2.25.1')});
test('Server continuation survives reload with same logical Session and two remaining items',async()=>{const f=await serverFixture();await f.api({action:'report',lessonId:lesson.id,report:serverReport(f,6)});const resumed=await createSpeakingService(f.store,()=> 'resume')({action:'prepare',schemaVersion:'2.25.1',lessonId:lesson.id,sourceFingerprint:Q.version(f.inv)});assert.equal(resumed.state.remainingCoverage.length,2);assert.equal(resumed.state.activeAttempt.items.length,2);assert.equal(resumed.state.speakingSessionId,f.prepared.state.speakingSessionId)});
test('Invalid optional correction annotation cannot create a false assessment',async()=>{const f=await serverFixture(),r=serverReport(f,6);r.correctionChecks=[{correctionId:'invented',oralTransfer:'passed'}];const result=await f.api({action:'report',lessonId:lesson.id,report:r});assert.equal(result.report.correctionChecks.length,0);assert.equal(result.state.completedCoverage.length,6)});
test('Previous production correction can be observed naturally through matching Vocabulary evidence',async()=>{const f=await serverFixture(),r=serverReport(f);const source=sourceContext(await f.store.source(),lesson.id).corrections.find(x=>x.target==='spouse'&&x.round==='production');const item=f.inv.find(x=>x.target==='spouse'),e=r.coverageChecks.find(x=>x.coverageId===item.coverageId);r.correctionChecks=[{correctionId:source.correctionId,originalAnswer:source.originalAnswer,gptSuggestedAnswer:source.gptSuggestedAnswer,learnerCorrection:source.learnerCorrection,writtenStatus:'not_checked',suggestedCorrection:'',oralTransfer:'needs_practice',newPrompt:e.newPrompt,learnerUtterance:e.learnerUtterance,reason:'The previous issue appeared again.'}];const result=await f.api({action:'report',lessonId:lesson.id,report:r});assert.equal(result.report.correctionChecks[0].oralTransfer,'needs_practice')});
test('Previous spelling correction remains not_tested without a spelling task',async()=>{const f=await serverFixture(),r=serverReport(f);const source=sourceContext(await f.store.source(),lesson.id).corrections.find(x=>x.round==='spelling');const item=f.inv.find(x=>x.target===source.target),e=r.coverageChecks.find(x=>x.coverageId===item.coverageId);r.correctionChecks=[{correctionId:source.correctionId,originalAnswer:source.originalAnswer,gptSuggestedAnswer:source.gptSuggestedAnswer,learnerCorrection:source.learnerCorrection,writtenStatus:'not_checked',suggestedCorrection:'',oralTransfer:'passed',newPrompt:e.newPrompt,learnerUtterance:e.learnerUtterance,reason:'Spoken normally.'}];const result=await f.api({action:'report',lessonId:lesson.id,report:r});assert.equal(result.report.correctionChecks[0].oralTransfer,'not_tested')});
test('Server rejects unknown attempt and stale preparation without writes',async()=>{const f=await serverFixture();const before=f.store.rows();const r=serverReport(f);r.continuationAttemptId='fake';await assert.rejects(()=>f.api({action:'report',lessonId:lesson.id,report:r}));await assert.rejects(()=>f.api({action:'prepare',schemaVersion:'2.25.1',lessonId:lesson.id,sourceFingerprint:'stale'}));assert.deepEqual(f.store.rows(),before)});
test('Two simultaneous prepares reuse one active logical Session',async()=>{const store=memoryStore();let id=0;const api=createSpeakingService(store,()=>String(++id));const c=sourceContext(await store.source(),lesson.id),fingerprint=Q.version(Q.inventory(c.lesson,c.corrections,{schemaVersion:'2.25.1'}));const [a,b]=await Promise.all([api({action:'prepare',schemaVersion:'2.25.1',lessonId:lesson.id,sourceFingerprint:fingerprint}),api({action:'prepare',schemaVersion:'2.25.1',lessonId:lesson.id,sourceFingerprint:fingerprint})]);assert.equal(a.state.speakingSessionId,b.state.speakingSessionId);assert.equal(store.rows().length,1)});
test('Concurrent duplicate report import remains idempotent',async()=>{const f=await serverFixture();const r=serverReport(f,6);await Promise.all([f.api({action:'report',lessonId:lesson.id,report:r}),f.api({action:'report',lessonId:lesson.id,report:r})]);assert.equal(f.store.rows()[0].state.attempts.length,1)});
test('Completed V2.25 Session starts a new round only when explicitly requested',async()=>{const f=await serverFixture();await f.api({action:'report',lessonId:lesson.id,report:serverReport(f)});const same=await f.api({action:'prepare',schemaVersion:'2.25.1',lessonId:lesson.id,sourceFingerprint:Q.version(f.inv)});assert(same.state.completed);const next=await f.api({action:'prepare',schemaVersion:'2.25.1',lessonId:lesson.id,sourceFingerprint:Q.version(f.inv),newSession:true});assert.notEqual(next.state.speakingSessionId,same.state.speakingSessionId);assert.equal(next.state.completedCoverage.length,0)});

test('Legacy clients prepare the V2.24 15-item contract until the site is upgraded',async()=>{const store=memoryStore();const api=createSpeakingService(store,()=> 'legacy-attempt');const c=sourceContext(await store.source(),lesson.id);const legacy=Q.inventory(c.lesson,c.corrections,{schemaVersion:'2.24.0'});const prepared=await api({action:'prepare',lessonId:lesson.id,sourceFingerprint:Q.version(legacy)});assert.equal(prepared.state.sessionCoverage.total,15);assert.equal(prepared.state.activeAttempt.schemaVersion,'2.24.0')});
test('A V2.24 client cannot mutate an existing V2.25 Session, but may read its status',async()=>{const f=await serverFixture();const c=sourceContext(await f.store.source(),lesson.id);const legacy=Q.inventory(c.lesson,c.corrections,{schemaVersion:'2.24.0'});await assert.rejects(()=>f.api({action:'prepare',lessonId:lesson.id,sourceFingerprint:Q.version(legacy)}),/重新載入網站/);const status=await f.api({action:'status',lessonId:lesson.id,sourceFingerprint:Q.version(legacy)});assert.equal(status.state.sessionCoverage.total,8);assert.equal(f.store.rows().length,1)});
