import test from 'node:test';
import assert from 'node:assert/strict';
import '../src/speaking-queue.js';
import { createSpeakingService } from '../src/speaking-service.mjs';
import { sourceContext } from '../src/source-context.mjs';
const Q = globalThis.EnglishSpeakingQueue;
const copy = x => structuredClone(x);
const lesson = {id:'fixture',title:'Family',curriculum:{mainVocabulary:['niece','spouse','ancestor','descendant','sibling'].map(term=>({term,meaning:term})),extendedVocabulary:[],grammar:[{rule:'稱謂後面加上名字時，兩者都需要大寫。'},{rule:'直接用稱謂代替人名時要大寫。'},{rule:'「誰的＋稱謂」中的稱謂用小寫。'}]}};
const corrections = ['spouse','descendant','sibling','niece','ancestor','sibling','descendant'].map((target,i)=>({lessonId:lesson.id,correctionId:'c'+i,target,component:'Vocabulary',round:i<4?'production':'spelling',prompt:'Use '+target,originalAnswer:'original '+i,gptSuggestedAnswer:'better '+i,learnerCorrection:'learner '+i}));
const items = Q.inventory(lesson,corrections);
const fresh = () => Q.prepare(Q.reconcile(null,items,{speakingSessionId:'logical-1',lessonId:lesson.id,lessonTitle:lesson.title}),'attempt-1');
function evidence(item,index) {
  const example=item.grammarTask==='title_with_name'?'Aunt Mary':item.grammarTask==='title_replacing_name'?'Good morning, Mom.':'my mom';
  return {coverageId:item.coverageId,sourceVersion:item.sourceVersion,taskMode:item.taskMode,phaseId:'lesson_application',sequence:index+1,status:'practiced',newPrompt:item.taskMode==='spelling_recall'?'Can you spell '+item.target+'?':item.kind==='grammar'?'Capital or lowercase in '+example+'?':'Tell me a new story using '+item.target,learnerUtterance:item.taskMode==='spelling_recall'?item.target.toUpperCase().split('').join('-'):item.kind==='grammar'?'It should be a capital letter.':'My '+item.target+' likes traveling.',utteranceReliability:'confirmed',transcriptionIssue:false,learnerFinished:true,modelOnly:false,coachSuppliedAnswer:false,newContext:true,grammarRuleId:item.coverageId,grammarTask:item.grammarTask,caseExample:example,correctionId:item.correctionId,transferFocus:'new subject and situation',letterSequence:item.target.toUpperCase().split('').join('-'),notes:'Actual learner attempt'};
}
function report(count=15) {
  return {type:'SPEAKING_REPORT',schemaVersion:'2.24.0',speakingSessionId:'logical-1',continuationAttemptId:'attempt-1',lessonId:lesson.id,completed:true,endReason:'completed',speakingMinutes:25,timeBasis:'measured',coverageChecks:items.slice(0,count).map(evidence),phaseProgress:Q.PHASES.map(phaseId=>({phaseId,status:'completed',notes:'actual '+phaseId})),finalChallenge:{sequence:50,newPrompt:'Tell a new integrated story.',learnerUtterance:'My sibling and spouse visited my niece.',utteranceReliability:'confirmed',transcriptionIssue:false,learnerFinished:true,independentProduction:true,coachSuppliedAnswer:false,feedbackGiven:true}};
}
test('Inventory has 5 vocabulary, 3 distinct capitalization rules, 4 production and 3 spelling corrections',()=>{assert.equal(items.length,15);assert.equal(new Set(items.map(x=>x.coverageId)).size,15);assert.equal(items.filter(x=>x.taskMode==='spelling_recall').length,3);assert.equal(items.filter(x=>x.evidenceType==='capitalization_decision').length,3)});
test('A: 14/15 cannot complete and keeps 14 valid records',()=>{const {state,report:r}=Q.applyReport(fresh(),report(14));assert.equal(r.completed,false);assert.equal(state.completedCoverage.length,14);assert.equal(state.remainingCoverage.length,1)});
test('B: GPT true with 10/15 is saved as OS false',()=>{const {report:r}=Q.applyReport(fresh(),report(10));assert.equal(r.gptClaimedCompleted,true);assert.equal(r.osVerifiedCompleted,false);assert.equal(r.sessionCoverage.practiced,10)});
test('C: full coverage without independent final is incomplete',()=>{const r=report();r.finalChallenge.independentProduction=false;assert.equal(Q.applyReport(fresh(),r).state.completed,false)});
test('D: prompt-only spouse is not production',()=>{const r=report();r.coverageChecks[1].learnerUtterance='We watch movies together.';const s=Q.applyReport(fresh(),r).state;assert.equal(s.remainingCoverage[0].target,'spouse');assert.equal(s.remainingCoverage[0].remainingReason,'coach_only_target')});
test('E: spoken ancestor passes production but not spelling',()=>{const r=report();r.coverageChecks.find(x=>x.taskMode==='spelling_recall').learnerUtterance='ancestor';const s=Q.applyReport(fresh(),r).state;assert(s.completedCoverage.some(x=>x.target==='ancestor'&&x.kind==='vocabulary'));assert(s.remainingCoverage.some(x=>x.target==='ancestor'&&x.taskMode==='spelling_recall'))});
test('F: 8/15 continuation retains logical ID and exactly 7 remaining; warmup retained',()=>{const a=Q.applyReport(fresh(),report(8)).state;const b=Q.prepare(a,'attempt-2');assert.equal(b.speakingSessionId,'logical-1');assert.equal(b.activeAttempt.id,'attempt-2');assert.equal(b.activeAttempt.items.length,7);assert.equal(b.completedCoverage.length,8);assert.equal(b.phaseProgress[0].status,'completed');const r=report();r.continuationAttemptId='attempt-2';r.coverageChecks=items.slice(8).map(evidence);assert.equal(Q.applyReport(b,r).state.completed,true)});
test('G: stale sourceVersion is not accepted; other evidence survives',()=>{const r=report();r.coverageChecks[0].sourceVersion='old';const s=Q.applyReport(fresh(),r).state;assert.equal(s.completedCoverage.length,14);assert.equal(s.completed,false)});
test('H: uncertain transcript does not count',()=>{const r=report();r.coverageChecks[0].utteranceReliability='uncertain';r.coverageChecks[0].transcriptionIssue=true;const s=Q.applyReport(fresh(),r).state;assert.equal(s.remainingCoverage[0].remainingReason,'unreliable_transcript');assert.equal(s.completedCoverage.length,14)});
test('Complete only with 15 valid items, all four phases and independent final',()=>assert.equal(Q.applyReport(fresh(),report()).state.completed,true));
test('Transcript auto-capitalization without explicit choice fails all grammar items',()=>{const r=report();r.coverageChecks.filter(x=>x.taskMode==='grammar_application').forEach(e=>e.learnerUtterance='Aunt Mary visits Mom.');assert.equal(Q.applyReport(fresh(),r).state.remainingCoverage.length,3)});
test('Wrong but reliable case choice counts as practice, no mastery field',()=>{const e=evidence(items[7],7);assert.equal(Q.assess(items[7],e).ok,true);assert(!Object.hasOwn(Q.applyReport(fresh(),report()).state,'mastery'))});
test('Reliable wrong spelling counts as practice, uncertain letters do not',()=>{const item=items.find(x=>x.taskMode==='spelling_recall');const e=evidence(item,1);e.learnerUtterance=e.letterSequence='A-N-S-E-S-T-O-R';assert(Q.assess(item,e).ok);e.utteranceReliability='likely';assert.equal(Q.assess(item,e).ok,false)});
test('Model-only response never fills a queue item',()=>{const r=report();r.coverageChecks[0].modelOnly=true;assert.equal(Q.applyReport(fresh(),r).state.remainingCoverage[0].remainingReason,'model_only')});
test('Answer fragment with learnerFinished=false is not accepted',()=>{const r=report();r.coverageChecks[0].learnerFinished=false;assert.equal(Q.applyReport(fresh(),r).state.completedCoverage.length,14)});
test('Grammar-specific ID and correction-specific ID cannot be merged by target',()=>{const r=report();r.coverageChecks[5].grammarRuleId=items[6].coverageId;r.coverageChecks[8].correctionId='c3';assert.equal(Q.applyReport(fresh(),r).state.completedCoverage.length,13)});
test('Final challenge cannot supply missing coverage',()=>{const r=report();r.coverageChecks[0].phaseId='final_challenge';assert.equal(Q.applyReport(fresh(),r).state.completed,false)});
test('Final before the last accepted task fails even with all coverage',()=>{const r=report();r.finalChallenge.sequence=7;assert.equal(Q.applyReport(fresh(),r).state.completed,false)});
test('Empty final utterance fails gate',()=>{const r=report();r.finalChallenge.learnerUtterance='';assert.equal(Q.applyReport(fresh(),r).state.completed,false)});
test('Missing one phase keeps full-coverage final incomplete',()=>{const r=report();r.phaseProgress[2].status='partial';assert.equal(Q.applyReport(fresh(),r).state.completed,false)});
test('Coach wrap-up + Yeah is not learner_agreed_stop',()=>{const r=report(8);r.completed=false;r.endReason='learner_agreed_stop';r.stopContext={externalReason:'long conversation',learnerWords:'Yeah.',coachInitiatedWrapUp:true};const s=Q.applyReport(fresh(),r).state;assert.equal(s.endReason,'incomplete');assert.equal(s.completedCoverage.length,8)});
test('Explicit external stop keeps valid evidence',()=>{const r=report(8);r.endReason='learner_agreed_stop';r.stopContext={externalReason:'Learner must leave for appointment',learnerWords:'I need to leave now, let us stop.',coachInitiatedWrapUp:false};assert.equal(Q.applyReport(fresh(),r).state.endReason,'learner_agreed_stop')});
test('Idempotent same attempt does not inflate time/evidence; conflicting payload rejected',()=>{const r=report(8),a=Q.applyReport(fresh(),r).state,b=Q.applyReport(a,r);assert.equal(b.duplicate,true);assert.equal(b.state.attempts.length,1);r.speakingMinutes=99;assert.throws(()=>Q.applyReport(a,r),/不同回報/)});
test('Later invalid retry does not erase earlier valid production',()=>{const r=report();r.coverageChecks.push({...r.coverageChecks[0],sequence:20,modelOnly:true});assert.equal(Q.applyReport(fresh(),r).state.completed,true)});
test('Changed source invalidates only changed coverage and final',()=>{const s=Q.applyReport(fresh(),report()).state;const next=copy(items);next[0].sourceVersion='new';const b=Q.reconcile(s,next);assert.equal(b.completedCoverage.length,14);assert.equal(b.finalChallengeStatus,null);assert.equal(b.completed,false)});
test('No time limit; 90 minutes retained and no unknown time fabricated',()=>{const r=report();r.speakingMinutes=90;assert.equal(Q.applyReport(fresh(),r).report.speakingMinutes,90);r.timeBasis='not_recorded';r.speakingMinutes=null;assert.equal(Q.applyReport(fresh(),r).report.speakingMinutes,null)});
test('Legacy versions stay separate; 2.24 and future versions use queue gate',()=>{for(const v of ['2.20.0','2.23.0','legacy'])assert.equal(Q.isQueueReport({schemaVersion:v}),false);assert(Q.isQueueReport({schemaVersion:'2.24.1'}));assert(Q.isQueueReport({schemaVersion:'2.25.0'}))});

// Exercise the actual server service against a revision-checking store, not a second validator.
const session={id:'written',lessonId:lesson.id,lessonTitle:lesson.title,answers:corrections.map((x,i)=>({id:'q'+i,component:x.component,round:x.round,target:x.target,prompt:x.prompt,userAnswer:x.originalAnswer,status:'answered'}))};
const grades={sessionId:session.id,importedAt:'2026-09-17',gradedAnswers:corrections.map((x,i)=>({id:'q'+i,status:'incorrect',better:x.gptSuggestedAnswer,corrected:true,correctionAnswer:x.learnerCorrection}))};
function memoryStore(){let db=new Map(),source={'english_os_lessons':JSON.stringify([lesson]),'english_os_sessions':JSON.stringify([session]),'english_os_gpt_reports':JSON.stringify([grades])};return {source:async()=>copy(source),get:async id=>copy(db.get(id)||null),latest:async id=>copy([...db.values()].filter(x=>x.lesson_id===id).at(-1)||null),save:async(s,r)=>{const prev=db.get(s.speakingSessionId);if(r===null?!!prev:prev?.revision!==r)return false;if(r===null&&[...db.values()].some(x=>x.lesson_id===s.lessonId&&!x.state.completed))return false;db.set(s.speakingSessionId,{lesson_id:s.lessonId,state:copy(s),revision:(r||0)+1});return true},changeSource:fn=>fn(source),rows:()=>copy([...db.values()])}}
async function serverFixture(){const store=memoryStore();let id=0;const api=createSpeakingService(store,()=>String(++id));const ctx=sourceContext(await store.source(),lesson.id);const inv=Q.inventory(ctx.lesson,ctx.corrections);const prepared=await api({action:'prepare',lessonId:lesson.id,sourceFingerprint:Q.version(inv)});return {store,api,inv,prepared};}
function serverReport(f,count=15){const r=report(count);r.speakingSessionId=f.prepared.state.speakingSessionId;r.continuationAttemptId=f.prepared.state.activeAttempt.id;r.coverageChecks=f.inv.slice(0,count).map(evidence);return r}
test('Server builds all 15 items from stored curriculum/source answers, ignoring caller queue',async()=>{const f=await serverFixture();assert.equal(f.inv.length,15);const result=await f.api({action:'report',lessonId:lesson.id,report:serverReport(f,10),queue:[]});assert.equal(result.state.completedCoverage.length,10);assert.equal(result.state.completed,false);assert.equal(f.store.rows()[0].state.attempts.length,1)});
test('Server continuation survives a reload, same session ID, 7-item attempt',async()=>{const f=await serverFixture();await f.api({action:'report',lessonId:lesson.id,report:serverReport(f,8)});const resumed=await createSpeakingService(f.store,()=> 'resume')({action:'prepare',lessonId:lesson.id,sourceFingerprint:Q.version(f.inv)});assert.equal(resumed.state.remainingCoverage.length,7);assert.equal(resumed.state.speakingSessionId,f.prepared.state.speakingSessionId);assert.equal(resumed.state.reports.length,1)});
test('Server import stores valid coverage despite invalid correction annotations',async()=>{const f=await serverFixture(),r=serverReport(f,8);r.correctionChecks=[{correctionId:'invented',oralTransfer:'passed'}];const result=await f.api({action:'report',lessonId:lesson.id,report:r});assert.equal(result.report.correctionChecks.length,0);assert.equal(result.state.completedCoverage.length,8)});
test('Server rejects unknown attempt, wrong lesson and stale preparation; no writes',async()=>{const f=await serverFixture();const before=f.store.rows();const r=serverReport(f);r.continuationAttemptId='fake';await assert.rejects(()=>f.api({action:'report',lessonId:lesson.id,report:r}));await assert.rejects(()=>f.api({action:'prepare',lessonId:lesson.id,sourceFingerprint:'stale'}));assert.deepEqual(f.store.rows(),before)});
test('Two simultaneous prepares reuse one active logical session',async()=>{const store=memoryStore();let id=0;const api=createSpeakingService(store,()=>String(++id));const c=sourceContext(await store.source(),lesson.id),fingerprint=Q.version(Q.inventory(c.lesson,c.corrections));const [a,b]=await Promise.all([api({action:'prepare',lessonId:lesson.id,sourceFingerprint:fingerprint}),api({action:'prepare',lessonId:lesson.id,sourceFingerprint:fingerprint})]);assert.equal(a.state.speakingSessionId,b.state.speakingSessionId);assert.equal(store.rows().length,1)});
test('Concurrent duplicate report import is idempotent under revision conflict',async()=>{const f=await serverFixture();const r=serverReport(f,8);await Promise.all([f.api({action:'report',lessonId:lesson.id,report:r}),f.api({action:'report',lessonId:lesson.id,report:r})]);assert.equal(f.store.rows()[0].state.attempts.length,1)});
test('Completed session creates new round only on explicit newSession',async()=>{const f=await serverFixture();await f.api({action:'report',lessonId:lesson.id,report:serverReport(f)});const same=await f.api({action:'prepare',lessonId:lesson.id,sourceFingerprint:Q.version(f.inv)});assert(same.state.completed);const next=await f.api({action:'prepare',lessonId:lesson.id,sourceFingerprint:Q.version(f.inv),newSession:true});assert.notEqual(next.state.speakingSessionId,same.state.speakingSessionId);assert.equal(next.state.completedCoverage.length,0)});
