const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const crypto=require('node:crypto');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const source=html.match(/<script>([\s\S]*?)<\/script>/)?.[1];
if(!source)throw new Error('Application script missing.');
const clone=value=>JSON.parse(JSON.stringify(value));
const lesson={id:'A',title:'家庭成員',curriculum:{lessonConcept:[{title:'Family',details:['People in a family'],sourcePages:[1]}],unclassifiedVocabulary:[{term:'relative',meaning:'親戚',sourcePages:[1]}],mainVocabulary:[{term:'spouse',meaning:'配偶',examples:['My spouse is kind.'],sourcePages:[2]}],extendedVocabulary:[{term:'descendant',meaning:'後代',examples:[],sourcePages:[3]}],grammar:[{rule:'Use an article before a singular count noun.',examples:['He is a teacher.'],sourcePages:[4]}],conversationReference:[{title:'At home',content:['How is your family?'],sourcePages:[5]}]}};
const oldSession={id:'sess_old',lessonId:'A',lessonTitle:'家庭成員',endedAt:'2026-09-30T00:00:00Z',answers:[{id:'sentence',component:'Vocabulary',kind:'open',round:'production',target:'spouse',question:'Use spouse in a sentence.',userAnswer:'My spouse good.',status:'answered',needsGPT:true}]};
const oldReport={type:'GPT_CHECK_REPORT',sessionId:'sess_old',lessonId:'A',lessonTitle:'家庭成員',gradedAnswers:[{id:'sentence',component:'Vocabulary',target:'spouse',status:'incorrect',original:'My spouse good.',better:'My spouse is good.',reason:'Add is.',corrected:false}]};
const archivedSpeaking={type:'SPEAKING_REPORT',speakingSessionId:'speak_archive',continuationAttemptId:'attempt_archive',lessonId:'A',serverVerified:true};
const remote={version:1,state:{english_os_lessons:JSON.stringify([lesson]),english_os_sessions:JSON.stringify([oldSession]),english_os_gpt_reports:JSON.stringify([oldReport]),english_os_learning_signals:JSON.stringify([{target:'archived-only',component:'Vocabulary',lessonId:'A',reason:'speaking_review',speakingReportKey:'archived'}]),english_os_lesson_state_A:JSON.stringify({vocabulary:{spouse:{meaning:{attempts:1,score:1,status:'developing'}}}}),english_os_speaking_reports:JSON.stringify([archivedSpeaking])},writes:0,speakingCalls:0};
remote.state.english_os_weaknesses=JSON.stringify({vocabulary:['spouse','not-in-materials'],grammar:['Use an article before a singular count noun.'],concept:[]});
function createApp(seed=new Map()){
 const nodes=new Map(),intervals=new Map(),copied=[];let sequence=0;
 class Storage{constructor(){this.m=new Map(seed)}get length(){return this.m.size}key(i){return [...this.m.keys()][i]??null}getItem(k){return this.m.get(String(k))??null}setItem(k,v){this.m.set(String(k),String(v))}removeItem(k){this.m.delete(String(k))}clear(){this.m.clear()}}
 function decode(v){return v.replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&')}
 class Element{constructor(id='',tag='div',attrs={}){this.id=id;this.tagName=tag.toUpperCase();this.value=attrs.value||'';this.className=attrs.class||'';this.style={};this.dataset={};this.attrs=attrs;this.children=[];this._html='';this._text='';this.disabled=false;this.parentElement={insertBefore:()=>{}};if(id)nodes.set(id,this);for(const [k,v]of Object.entries(attrs))if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=v;this.classList={contains:x=>this.className.split(' ').includes(x),add:x=>{if(!this.classList.contains(x))this.className+=' '+x},remove:x=>{this.className=this.className.split(' ').filter(c=>c!==x).join(' ')},toggle:(x,v)=>{(v??!this.classList.contains(x))?this.classList.add(x):this.classList.remove(x)}}}
  set innerHTML(value){this._html=value;this._text='';this.children=parse(value);if(this.tagName==='SELECT')this.value=this.children.find(c=>c.tagName==='OPTION')?.attrs.value||''}get innerHTML(){return this._html}
  set textContent(value){this._text=String(value);this._html=''}get textContent(){return this._text||decode(this._html.replace(/<[^>]*>/g,''))}
  querySelectorAll(selector){return query(this.children,selector)}contains(){return false}dispatchEvent(event){this['on'+event.type]?.({target:this})}focus(){}scrollIntoView(){}
 }
 function parse(markup){return [...markup.matchAll(/<(\w+)([^>]*)>/g)].map(match=>{const attrs={};for(const part of match[2].matchAll(/([\w-]+)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))/g))attrs[part[1]]=decode(part[2]??part[3]??part[4]);return new Element(attrs.id||'',match[1],attrs)})}
 const all=parse(html);
 function query(elements,selector){if(selector==='.nav button')return all.filter(e=>e.tagName==='BUTTON'&&e.dataset.page);if(selector==='.tab'||selector==='.page')return all.filter(e=>e.classList.contains(selector.slice(1)));if(selector==='.topic-input')return (nodes.get('learnAnswerArea')?.children||[]).filter(e=>e.classList.contains('topic-input'));if(selector.startsWith('[data-'))return elements.filter(e=>Object.hasOwn(e.attrs,selector.slice(1,-1)));return []}
 const localStorage=new Storage();
 const sandbox={crypto,console,Storage,localStorage,document:{getElementById:id=>nodes.get(id)||null,querySelectorAll:selector=>query(all,selector),activeElement:{tagName:'BODY'},createElement:tag=>new Element('',tag)},navigator:{clipboard:{writeText:async value=>{copied.push(value)}}},setInterval:fn=>{intervals.set(++sequence,fn);return sequence},clearInterval:id=>intervals.delete(id),setTimeout:()=>++sequence,clearTimeout:()=>{},fetch:async(url,options={})=>{if(url.includes('/functions/v1/speaking-queue')){remote.speakingCalls++;throw new Error('Old Speaking endpoint invoked.')}if(url.includes('/rest/v1/english_os_state')){if(options.method==='POST'){const body=JSON.parse(options.body);remote.state=clone(body.state);remote.version=body.version;remote.writes++;return {ok:true,json:async()=>[]}}return {ok:true,json:async()=>[{state:clone(remote.state),version:remote.version}]}}return {ok:true,json:async()=>[]}},confirm:()=>true,Event:class{constructor(type){this.type=type}},Math,Date,JSON,Map,Set,encodeURIComponent};
 sandbox.window=sandbox;sandbox.addEventListener=()=>{};
 vm.createContext(sandbox);vm.runInContext(source,sandbox);
 return {run:code=>vm.runInContext(code,sandbox),json:code=>clone(vm.runInContext(code,sandbox)),get:id=>nodes.get(id),localStorage,copied};
}
const tick=()=>new Promise(resolve=>setImmediate(resolve));
async function main(){
 const app=createApp();await tick();
 const {run,json,get,localStorage,copied}=app;
 assert.match(html,/<section id="speaking" class="page">[\s\S]*?準備今天的 Speaking[\s\S]*?<\/section>/);
 assert(!html.includes('id="copySpeakingBrief"'));
 assert(!html.includes('id="importSpeakingReport"'));
 assert(!html.includes('/functions/v1/speaking-queue'));
 assert(!html.includes('id="mobileAddress"'));
 assert(!html.includes('手機與電腦共用同一份資料'));
 assert.match(html,/<details class="dashboard-guide"><summary>新增教材流程<\/summary>/);
 assert(get('syncStatus').textContent.includes('Cloud sync on'));
 const initialState=JSON.stringify(json('localSyncSnapshot()'));
 get('dashboardToSpeaking').onclick();assert(get('speaking').classList.contains('active'));
 get('dashboardToLearning').onclick();assert(get('learn').classList.contains('active'));
 assert.equal(JSON.stringify(json('localSyncSnapshot()')),initialState);
 console.log('PASS Cloud Sync explanation card removed, header status retained, and dashboard shortcuts navigate without data changes');
 run('showPage("speaking")');assert(get('speaking').classList.contains('active'));
 assert(get('mobilePage').value==='speaking');
 assert.equal(get('speakingLesson').value,'A');
 assert(!html.includes('id="importSpeakingReport"'));
 assert(get('speakingReportInput'));assert(get('saveSpeakingReport'));assert(get('speakingReportList'));
 console.log('PASS Speaking navigation, Brief and report inbox controls; old import endpoint absent');
 assert.equal(JSON.parse(localStorage.getItem('english_os_lessons'))[0].curriculum.mainVocabulary[0].term,'spouse');
 for(const section of ['lessonConcept','mainVocabulary','extendedVocabulary','grammar','conversationReference'])assert.deepEqual(JSON.parse(localStorage.getItem('english_os_lessons'))[0].curriculum[section],lesson.curriculum[section]);
 run('showPage("materials")');assert(get('lessons').innerHTML.includes('家庭成員'));
 run('showPage("dashboard")');assert(get('dashLessons').innerHTML.includes('家庭成員'));
 console.log('PASS Dashboard, Materials, and all five curriculum sections preserved');
 run('showPage("speaking")');
 const beforeBrief=JSON.stringify(json('localSyncSnapshot()')),writesBeforeBrief=remote.writes;
 get('prepareSpeakingBrief').onclick();
 const firstBrief=JSON.parse(get('speakingBriefPreview').value);
 assert.equal(firstBrief.type,'SPEAKING_BRIEF');assert.equal(firstBrief.schemaVersion,'2.1');
 assert.equal(firstBrief.lessonId,'A');assert.equal(firstBrief.lessonTitle,'家庭成員');
 for(const key of ['mainVocabulary','extendedVocabulary','grammar','conversationReference'])assert.deepEqual(firstBrief[key],lesson.curriculum[key]);
 assert(!Object.hasOwn(firstBrief,'reviewItems'));
 assert(!Object.hasOwn(firstBrief,'previousWeaknesses'));
 assert(firstBrief.targetPlan.eligibleTargets.every(x=>x.lessonId==='A'&&x.source!=='reviewItems'));
 assert(!JSON.stringify(firstBrief).includes('archived-only'));
 assert(!JSON.stringify(firstBrief).includes('not-in-materials'));
 assert.equal(firstBrief.coachInstructions.mode,'adaptive_lesson_speaking');
 assert.equal(firstBrief.coachInstructions.targetSelection.currentLessonCoverageRequired,true);
 assert.equal(firstBrief.coachInstructions.targetSelection.onlyCurrentLessonTargets,true);
 assert.equal(firstBrief.coachInstructions.interactionRules.doNotProvideModelAnswerBeforeAttempt,true);
 assert.equal(firstBrief.coachInstructions.interactionRules.silenceDoesNotEqualCompletion,true);
 assert.equal(firstBrief.coachInstructions.questionHandling.answerQuestionImmediately,true);
 assert.equal(firstBrief.coachInstructions.correction.preserveLearnerOriginal,true);
 assert.deepEqual(firstBrief.coachInstructions.sessionFlow,['warm_up','current_lesson_application','final_challenge']);
 assert.equal(firstBrief.coachInstructions.turnCompletion.allowedEncouragement,'Take your time.');
 assert.equal(firstBrief.coachInstructions.turnCompletion.uncertainCompletionQuestion,'Are you still thinking?');
 assert.equal(firstBrief.coachInstructions.completion.timeLimit,false);
 assert.equal(firstBrief.targetPlan.currentTarget.target,'spouse');
 assert(firstBrief.targetPlan.remainingTargets.some(x=>x.target==='spouse'));
 assert.deepEqual(firstBrief.targetPlan.practicedTargets,[]);
 await get('copySpeakingV2Brief').onclick();assert.equal(copied.at(-1),get('speakingBriefPreview').value);
 assert.equal(JSON.stringify(json('localSyncSnapshot()')),beforeBrief);assert.equal(remote.writes,writesBeforeBrief);
 const sourceSnapshot=new Map(['english_os_learning_signals','english_os_weaknesses','english_os_lesson_state_A'].map(key=>[key,localStorage.getItem(key)]));
 localStorage.setItem('english_os_learning_signals',JSON.stringify([{lessonId:'A',component:'Vocabulary',target:'other-target',reason:'speaking_review'}]));
 localStorage.setItem('english_os_weaknesses',JSON.stringify({vocabulary:['other-target']}));
 localStorage.setItem('english_os_lesson_state_A',JSON.stringify({vocabulary:{spouse:{meaning:{status:'weak'}}}}));
 assert.deepEqual(JSON.parse(JSON.stringify(run('buildSpeakingV2Brief("A")'))),firstBrief);
 for(const [key,value] of sourceSnapshot)localStorage.setItem(key,value);
 console.log('PASS Speaking Brief uses only selected curriculum; Review and learning-state changes cannot enter its targets');
 get('saveSpeakingReport').onclick();assert.match(get('speakingReportStatus').textContent,/請先貼上/);
 const beforeReport=json('localSyncSnapshot()');
 const pastedReport='SPEAKING REPORT\nLesson: 家庭成員\nMy sentence: My spouse is kind.\n<unsafe> & words';
 get('speakingReportInput').value=pastedReport;get('saveSpeakingReport').onclick();
 const inboxKey='english_os_speaking_report_inbox_v2';
 let inbox=JSON.parse(localStorage.getItem(inboxKey));
 assert.equal(inbox.length,1);assert.equal(inbox[0].lessonId,'A');assert.equal(inbox[0].text,pastedReport);assert.equal(inbox[0].verification,'not_validated');
 assert(get('speakingReportList').innerHTML.includes('&lt;unsafe&gt; &amp; words'));
 assert(!get('speakingReportList').innerHTML.includes('<unsafe>'));
 assert.equal(get('speakingReportInput').value,'');
 for(const [key,value] of Object.entries(beforeReport))assert.equal(localStorage.getItem(key),value,`Report save changed ${key}`);
 get('speakingReportInput').value=pastedReport;get('saveSpeakingReport').onclick();
 assert.equal(JSON.parse(localStorage.getItem(inboxKey)).length,1);
 console.log('PASS report paste, exact-text preservation, escaping, empty-input handling, idempotence, and no other data mutation');
 const corrupt=createApp(new Map([[inboxKey,'{broken']]));await tick();corrupt.run('showPage("speaking")');
 corrupt.get('speakingReportInput').value='A new report';corrupt.get('saveSpeakingReport').onclick();
 assert.equal(corrupt.localStorage.getItem(inboxKey),'{broken');
 assert.match(corrupt.get('speakingReportStatus').textContent,/未覆寫原始資料/);
 console.log('PASS unreadable existing report inbox is never overwritten');
 run('showPage("add")');get('json').value=JSON.stringify({lessonTitle:'新教材',lessonConcept:[{title:'New concept'}],mainVocabulary:[{term:'friend',meaning:'朋友'}],extendedVocabulary:[{term:'acquaintance',meaning:'熟人'}],grammar:[{rule:'Present tense'}],conversationReference:[{title:'Greeting',content:['Hello']}],unclassifiedVocabulary:[]});
 await get('preview').onclick();assert(get('concept').innerHTML.includes('New concept'));
 await get('save').onclick();assert.equal(JSON.parse(localStorage.getItem('english_os_lessons')).length,2);
 assert.equal(JSON.parse(localStorage.getItem('english_os_lessons'))[0].curriculum.mainVocabulary[0].term,'spouse');
 console.log('PASS Add Material preview/save without changing the existing lesson');
 const savedLessons=JSON.parse(localStorage.getItem('english_os_lessons')),newLesson=savedLessons[1];
 run('showPage("speaking")');get('speakingLesson').value=newLesson.id;get('speakingLesson').onchange();
 assert(!get('speakingReportList').innerHTML.includes('My spouse is kind.'));
 get('speakingReportInput').value='SPEAKING REPORT\nLesson: 新教材';get('saveSpeakingReport').onclick();
 inbox=JSON.parse(localStorage.getItem(inboxKey));assert.equal(inbox.length,2);assert.equal(inbox[1].lessonId,newLesson.id);
 get('speakingLesson').value='A';get('speakingLesson').onchange();assert(get('speakingReportList').innerHTML.includes('My spouse is kind.'));
 get('speakingLesson').value=newLesson.id;get('speakingLesson').onchange();
 assert(get('speakingReportList').innerHTML.includes('Lesson: 新教材'));
 console.log('PASS saved reports remain associated with their selected lesson');
 get('prepareSpeakingBrief').onclick();const freshBrief=JSON.parse(get('speakingBriefPreview').value);
 assert.deepEqual(freshBrief.mainVocabulary,newLesson.curriculum.mainVocabulary);
 assert.deepEqual(freshBrief.extendedVocabulary,newLesson.curriculum.extendedVocabulary);
 assert.deepEqual(freshBrief.grammar,newLesson.curriculum.grammar);
 assert.deepEqual(freshBrief.conversationReference,newLesson.curriculum.conversationReference);
 assert(!freshBrief.mainVocabulary.some(x=>x.term==='spouse'));
 const minimal={id:'minimal',title:'只有主單字',curriculum:{mainVocabulary:[{term:'river',meaning:'河流'}]}};
 localStorage.setItem('english_os_lessons',JSON.stringify([...savedLessons,minimal]));
 run('showPage("speaking")');get('speakingLesson').value='minimal';get('speakingLesson').onchange();
 get('prepareSpeakingBrief').onclick();const minimalBrief=JSON.parse(get('speakingBriefPreview').value);
 assert.deepEqual(minimalBrief.mainVocabulary,minimal.curriculum.mainVocabulary);
 for(const key of ['extendedVocabulary','grammar','conversationReference'])assert.deepEqual(minimalBrief[key],[]);
 assert(!JSON.stringify(minimalBrief).includes('acquaintance'));
 localStorage.setItem('english_os_lessons',JSON.stringify(savedLessons));
 run('showPage("speaking")');assert.equal(get('speakingBriefPreview').value,'');
 console.log('PASS selected new lesson is dynamic; absent optional curriculum stays empty; stale preview clears');
 run('showPage("learn")');get('learnLesson').value='A';await get('startLearning').onclick();
 assert(json('learnSession&&learnSession.status')==='in_progress');assert(json('learnItems.length')>0);
 await get('endLearning').onclick();assert(JSON.parse(localStorage.getItem('english_os_sessions')).length===2);
 assert.equal(JSON.parse(localStorage.getItem('english_os_sessions'))[0].id,'sess_old');
 console.log('PASS Learning Session starts, ends, and preserves earlier sessions');
 run('showPage("correction")');assert(get('correctionList').innerHTML.includes('spouse'));
 assert(json('correctionItems().length')>0);get('corr_0').value='My spouse is good.';run('completeCorrection(0)');
 assert.equal(JSON.parse(localStorage.getItem('english_os_gpt_reports'))[0].gradedAnswers[0].corrected,true);
 console.log('PASS Correction renders, saves an answer, and preserves the GPT report');
 run('showPage("review")');const review=json('buildReviewQueue()');assert(review.some(x=>x.target==='spouse'));
 assert(review.some(x=>x.target==='archived-only'&&x.reasons.includes('speaking_review')));
 assert.equal(run('reviewReasonLabel("speaking_review")'),'Speaking 需要複習');
 assert(JSON.parse(localStorage.getItem('english_os_learning_signals')).some(x=>x.target==='archived-only'));
 console.log('PASS Review retains historical Speaking signals and its previous labels');
 const preserved=JSON.parse(localStorage.getItem('english_os_speaking_reports'));
 assert.deepEqual(preserved,[archivedSpeaking]);
 await run('cloudSave()');assert(remote.writes>0);assert.deepEqual(JSON.parse(remote.state.english_os_speaking_reports),[archivedSpeaking]);
 assert.equal(JSON.parse(remote.state[inboxKey]).length,2);
 const before=clone(remote.state);const reloaded=createApp();await tick();
 assert.deepEqual(reloaded.json('localSyncSnapshot()'),before);
 assert(reloaded.get('dashLessons').innerHTML.includes('家庭成員'));
 assert(reloaded.get('dashLessons').innerHTML.includes('新教材'));
 assert.equal(JSON.parse(reloaded.localStorage.getItem('english_os_sessions')).length,2);
 assert.deepEqual(JSON.parse(reloaded.localStorage.getItem('english_os_lesson_state_A')),JSON.parse(remote.state.english_os_lesson_state_A));
 assert.deepEqual(JSON.parse(reloaded.localStorage.getItem('english_os_speaking_reports')),[archivedSpeaking]);
 reloaded.run('showPage("speaking")');assert.equal(JSON.parse(reloaded.localStorage.getItem(inboxKey)).length,2);
 assert(reloaded.get('speakingReportList').innerHTML.includes('My spouse is kind.'));
 assert.equal(remote.speakingCalls,0);
 console.log('PASS Cloud Sync, reload, archived records, and zero Speaking endpoint calls');
 console.log('ALL PASS: 13 integration checks');
}
if(require.main===module)main().catch(error=>{console.error(error);process.exitCode=1});
module.exports={createApp,remote,tick};
