const vm=require('vm'),fs=require('fs'),assert=require('assert/strict');
const html=fs.readFileSync(require('path').join(__dirname,'../index.html'),'utf8'),source=html.match(/<script>([\s\S]*?)<\/script>/)[1];
class Storage{constructor(){this.m=new Map()}get length(){return this.m.size}key(i){return [...this.m.keys()][i]??null}getItem(k){return this.m.get(String(k))??null}setItem(k,v){this.m.set(String(k),String(v))}removeItem(k){this.m.delete(String(k))}clear(){this.m.clear()}}
const nodes=new Map(),intervals=new Map();let sequence=0,clipboard='';
function decode(v){return v.replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&')}
class Element{constructor(id='',tag='div',attrs={}){this.id=id;this.tagName=tag.toUpperCase();this.value=attrs.value||'';this.className=attrs.class||'';this.style={};this.dataset={};this.attrs=attrs;this.children=[];this._html='';this._text='';this.disabled=false;this.parentElement={insertBefore:()=>{}};if(id)nodes.set(id,this);for(const [k,v]of Object.entries(attrs))if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=v;this.classList={contains:x=>this.className.split(' ').includes(x),add:x=>{if(!this.classList.contains(x))this.className+=' '+x},remove:x=>{this.className=this.className.split(' ').filter(c=>c!==x).join(' ')},toggle:(x,v)=>{(v??!this.classList.contains(x))?this.classList.add(x):this.classList.remove(x)}}}
 set innerHTML(s){this._html=s;this._text='';this.children=parse(s);if(this.tagName==='SELECT')this.value=this.children.find(c=>c.tagName==='OPTION')?.attrs.value||''}get innerHTML(){return this._html}
 set textContent(s){this._text=String(s);this._html=''}get textContent(){return this._text||decode(this._html.replace(/<[^>]*>/g,''))}
 querySelectorAll(s){return query(this.children,s)}contains(){return false}dispatchEvent(e){this['on'+e.type]?.({target:this})}
}
function parse(s){return [...s.matchAll(/<(\w+)([^>]*)>/g)].map(m=>{const attrs={};for(const a of m[2].matchAll(/([\w-]+)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))/g))attrs[a[1]]=decode(a[2]??a[3]??a[4]);return new Element(attrs.id||'',m[1],attrs)})}
const all=parse(html);
function query(arr,s){if(s==='.nav button')return all.filter(e=>e.tagName==='BUTTON'&&e.dataset.page);if(s==='.tab'||s==='.page')return all.filter(e=>e.classList.contains(s.slice(1)));if(s==='.topic-input')return (nodes.get('learnAnswerArea')?.children||[]).filter(e=>e.classList.contains('topic-input'));if(s.startsWith('[data-'))return arr.filter(e=>Object.hasOwn(e.attrs,s.slice(1,-1)));return []}
const sandbox={console,Storage,localStorage:new Storage(),document:{getElementById:id=>nodes.get(id)||null,querySelectorAll:s=>query(all,s),activeElement:{tagName:'BODY'},createElement:tag=>new Element('',tag)},navigator:{clipboard:{writeText:async x=>{clipboard=x}}},setInterval:fn=>{intervals.set(++sequence,fn);return sequence},clearInterval:id=>intervals.delete(id),setTimeout:()=>++sequence,clearTimeout:()=>{},fetch:async()=>({ok:true,json:async()=>[]}),confirm:()=>true,Event:class{constructor(type){this.type=type}},Math,Date,JSON,Map,Set,encodeURIComponent};sandbox.window=sandbox;sandbox.addEventListener=()=>{};vm.createContext(sandbox);vm.runInContext(source,sandbox);
function run(s){return vm.runInContext(s,sandbox)}
function json(s){return JSON.parse(JSON.stringify(run(s)))}
let passed=0;const results=[];
async function test(name,fn){try{await fn();passed++;results.push('PASS '+name)}catch(e){results.push('FAIL '+name+'\n'+e.stack);throw e}}
const snapshot=()=>json('localSyncSnapshot()');
setImmediate(async()=>{try{
run(`
const fixtureLessons=[{id:'A',title:'家庭成員',curriculum:{lessonConcept:[],unclassifiedVocabulary:[],mainVocabulary:[{term:'spouse',meaning:'配偶',examples:[]},{term:'descendant',meaning:'後代',examples:[]},{term:'niece',meaning:'姪女',examples:[]},{term:'ancestor',meaning:'祖先',examples:[]},{term:'sibling',meaning:'兄弟姊妹',examples:[]}],extendedVocabulary:[],grammar:[{rule:'稱謂後面加上名字時，兩者都需要大寫。'},{rule:'直接用稱謂代替人名時要大寫。'},{rule:'「誰的＋稱謂」中的稱謂用小寫。'}],conversationReference:[]}},{id:'B',title:'另一課',curriculum:{lessonConcept:[],unclassifiedVocabulary:[],mainVocabulary:[{term:'spouse',meaning:'配偶',examples:[]}],extendedVocabulary:[],grammar:[],conversationReference:[]}}];
localStorage.setItem('english_os_lessons',JSON.stringify(fixtureLessons));
const sessionA={id:'A1',lessonId:'A',lessonTitle:'家庭成員',activeSeconds:125,endedAt:'2026-09-14T11:00:00Z',answers:[
{id:'sentence',target:'spouse',component:'Vocabulary',kind:'open',round:'production',question:'Use spouse in a sentence.',userAnswer:' I hope your name in spouse. ',intendedChinese:'希望你的名字出現在我的身分證配偶欄。',needsGPT:true},
{id:'pending',target:'descendant',component:'Vocabulary',kind:'open',question:'Use descendant.',userAnswer:'King descendant is he.',needsGPT:true},
{id:'v_topic_meaning',target:'English → Chinese',component:'Vocabulary',kind:'vocab_topic_meaning',rows:{spouse:{meaningAnswer:'妻子',prompt:'spouse',referenceAnswer:'配偶'},forgotten:{meaningAnswer:'',meaningForgot:true,prompt:'forgotten',referenceAnswer:'忘記的'},missing:{meaningAnswer:'wrong',meaningPromptMissing:true,prompt:'missing'},blank:{meaningAnswer:'',prompt:'blank'}}},
{id:'v_topic_spelling',component:'Vocabulary',kind:'vocab_topic_spelling',rows:{spouse:{spellingAnswer:'spouce',prompt:'配偶'}}}
]};
const sessionB={id:'B1',lessonId:'B',lessonTitle:'另一課',activeSeconds:5,endedAt:'2026-09-14T10:00:00Z',answers:[{id:'sentence',target:'spouse',component:'Vocabulary',kind:'open',question:'Another question.',userAnswer:'OTHER LESSON ORIGINAL',needsGPT:true}]};
localStorage.setItem('english_os_sessions',JSON.stringify([sessionA,sessionB]));
const reportA={sessionId:'A1',lessonId:'A',importedAt:'2026-09-14T12:00:00Z',gradedAnswers:[
{id:'sentence',target:'FAKE TARGET',component:'Vocabulary',status:'incorrect',original:'FAKE GPT ORIGINAL',better:'I hope your name will be in the spouse section of my ID card.',whatWasRight:'有運用 spouse。',reason:'補上完整動詞。',ruleOrPattern:'I hope + clause.',similarExamples:[{english:'I hope you are happy.',chinese:'我希望你快樂。'}],corrected:true,correctionAnswer:' I hope your name will appear in the spouse section of my ID card. ',correctedAt:'2026-09-14T13:00:00Z'},
{id:'pending',status:'incorrect',better:'He is a descendant of that king.',corrected:false,correctionAnswer:'UNSAVED DRAFT'},
{id:'v_topic_meaning::spouse',status:'incorrect',better:'配偶',corrected:true,correctionAnswer:'配偶'},
{id:'v_topic_meaning::forgotten',status:'incorrect',better:'忘記的',corrected:false},
{id:'v_topic_meaning::missing',status:'incorrect',better:'SHOULD NOT ENTER'},
{id:'v_topic_meaning::blank',status:'incorrect',better:'SHOULD NOT ENTER'},
{id:'v_topic_spelling::spouse',status:'incorrect',better:'spouse',corrected:false},
{id:'v_topic_meaning',target:'English → Chinese',status:'incorrect',original:'undefined'}]};
const reportB={sessionId:'B1',lessonId:'B',importedAt:'2026-09-14T12:00:00Z',gradedAnswers:[{id:'sentence',status:'incorrect',better:'OTHER GPT SUGGESTION',corrected:true,correctionAnswer:'OTHER LEARNER CORRECTION'}]};
localStorage.setItem('english_os_gpt_reports',JSON.stringify([reportA,reportB]));
populateSpeakingLessons();$('speakingLesson').value='A';
`);
await test('Selected lesson carries original, GPT suggestion, and saved correction separately',()=>{const x=json('speakingHandoffData("A").currentLessonCorrections.find(x=>x.itemId==="sentence")');assert.equal(x.originalAnswer,' I hope your name in spouse. ');assert.equal(x.gptSuggestedAnswer,'I hope your name will be in the spouse section of my ID card.');assert.equal(x.learnerCorrection,' I hope your name will appear in the spouse section of my ID card. ');assert.equal(x.target,'spouse');assert.equal(x.intendedChinese,'希望你的名字出現在我的身分證配偶欄。')});
await test('Teaching pattern and examples survive handoff',()=>{const x=json('speakingHandoffData("A").currentLessonCorrections.find(x=>x.itemId==="sentence")');assert.equal(x.teachingFeedback.ruleOrPattern,'I hope + clause.');assert.equal(x.teachingFeedback.similarExamples[0].chinese,'我希望你快樂。')});
await test('Saved correction starts unverified and not mastered',()=>{const x=json('speakingCorrectionRecords().find(x=>x.sessionId==="A1"&&x.itemId==="sentence")');assert.equal(x.correctionStatus,'corrected_needs_review');assert.equal(x.writtenValidationStatus,'not_checked');assert.equal(x.oralValidationStatus,'not_tested')});
await test('Unsubmitted draft is not falsely passed as a learner correction',()=>{const x=json('speakingCorrectionRecords().find(x=>x.itemId==="pending")');assert.equal(x.learnerCorrection,null);assert.equal(x.correctionStatus,'not_corrected')});
await test('Missing questions, blanks and unresolved legacy page excluded',()=>{const x=json('speakingCorrectionRecords()');assert(!x.some(x=>['missing','blank','English → Chinese'].includes(x.target)));assert.equal(x.length,6)});
await test('Forgotten word retains identity and empty original answer',()=>{const x=json('speakingCorrectionRecords().find(x=>x.target==="forgotten")');assert.equal(x.originalAnswer,'');assert.equal(x.answerStatus,'forgot');assert.equal(x.learnerCorrection,null)});
await test('Same word across sessions and directions keeps distinct IDs',()=>{const x=json('speakingCorrectionRecords().filter(x=>x.target==="spouse")');assert.equal(new Set(x.map(x=>x.correctionId)).size,4)});
await test('Another lesson is clearly separated as related review',()=>{const x=json('speakingHandoffData("A")');assert(x.currentLessonCorrections.every(x=>x.lessonId==='A'));assert.equal(x.olderReviewCorrections.length,1);assert.equal(x.olderReviewCorrections[0].originalAnswer,'OTHER LESSON ORIGINAL')});
await test('Newer duplicate report takes precedence over older incorrect report',()=>{run(`localStorage.setItem('english_os_gpt_reports',JSON.stringify([reportA,reportB,{...reportA,importedAt:'2026-09-15T00:00:00Z',gradedAnswers:[{id:'sentence',status:'correct'}]}]))`);assert.equal(json('speakingCorrectionRecords().filter(x=>x.lessonId==="A")').length,0);run(`localStorage.setItem('english_os_gpt_reports',JSON.stringify([reportA,reportB]))`)});
run(`
function makeSpeakingReport(){const c=speakingHandoffData('A').currentLessonCorrections.find(c=>c.itemId==='sentence');return {type:'SPEAKING_REPORT',schemaVersion:'2.19.1',speakingSessionId:'test-speaking-1',lessonId:'A',correctionChecks:[{correctionId:c.correctionId,...speakingCorrectionSnapshot(c),writtenStatus:'correct',oralTransfer:'passed',newPrompt:'Introduce your spouse to a new colleague.',learnerUtterance:'This is my spouse, Alex.',reason:'書面句子完整，新情境也正確使用 spouse。'}],targetsToReview:[],grammarToReview:[],completed:true}}
`);
await test('Import saves independent written and oral checks',()=>{const before=run('localStorage.getItem("english_os_gpt_reports")');const r=json('saveSpeakingReport(makeSpeakingReport())');assert.equal(r.correctionChecks[0].writtenStatus,'correct');assert.equal(r.correctionChecks[0].oralTransfer,'passed');assert.equal(r.correctionChecks[0].contextSnapshot.learnerCorrection,' I hope your name will appear in the spouse section of my ID card. ');assert.equal(run('localStorage.getItem("english_os_gpt_reports")'),before)});
await test('Speaking check does not mark mastered or overwrite learning scores',()=>{assert.equal(run('localStorage.getItem("english_os_lesson_state_A")'),null);assert.equal(json('speakingCorrectionRecords().find(x=>x.itemId==="sentence"&&x.lessonId==="A")').correctionStatus,'corrected_needs_review');assert(json('buildReviewQueue()').some(x=>x.target==='spouse'))});
await test('Legacy writing validation retained; absent oral reliability is not silently confirmed',()=>{const x=json('speakingCorrectionRecords().find(x=>x.itemId==="sentence"&&x.lessonId==="A")');assert.equal(x.writtenValidationStatus,'correct');assert.equal(x.oralValidationStatus,'not_tested');assert.equal(x.previousSpeakingAssessment.oral,null);assert.equal(x.previousSpeakingAssessment.unverifiedOral.reportedOutcome,'passed')});
await test('Duplicate import is idempotent',()=>{run('saveSpeakingReport(makeSpeakingReport())');assert.equal(json('JSON.parse(localStorage.getItem("english_os_speaking_reports"))').length,1)});
await test('Editing saved correction invalidates prior validation context',()=>{run(`const revised=JSON.parse(localStorage.getItem('english_os_gpt_reports'));revised[0].gradedAnswers[0].correctionAnswer='Another revision';localStorage.setItem('english_os_gpt_reports',JSON.stringify(revised))`);const x=json('speakingCorrectionRecords().find(x=>x.itemId==="sentence"&&x.lessonId==="A")');assert.equal(x.writtenValidationStatus,'not_checked');assert.equal(x.oralValidationStatus,'not_tested');run(`localStorage.setItem('english_os_gpt_reports',JSON.stringify([reportA,reportB]))`)});
async function rejects(name,mutation){await test(name,()=>{const before=snapshot();run(`var invalid=makeSpeakingReport();invalid.speakingSessionId='invalid-test';${mutation}`);assert.throws(()=>run('saveSpeakingReport(invalid)'));assert.deepEqual(snapshot(),before)})}
await rejects('Stale correction answer rejected without data writes',`invalid.correctionChecks[0].learnerCorrection='STALE';`);
await rejects('Wrong original snapshot rejected',`invalid.correctionChecks[0].originalAnswer='FAKE';`);
await rejects('Unknown correction ID rejected',`invalid.correctionChecks[0].correctionId='missing-id';`);
await rejects('Duplicate correction entries rejected',`invalid.correctionChecks.push(invalid.correctionChecks[0]);`);
await rejects('Oral pass requires actual new question and learner utterance',`invalid.correctionChecks[0].learnerUtterance='';`);
await rejects('Oral pass with missing new scenario rejected',`invalid.correctionChecks[0].newPrompt='';`);
await rejects('Unknown written status rejected',`invalid.correctionChecks[0].writtenStatus='mastered';`);
await rejects('Revision needed requires a suggested correction',`invalid.correctionChecks[0].writtenStatus='needs_revision';`);
await rejects('Unsubmitted correction cannot be marked written correct',`const c=speakingHandoffData('A').currentLessonCorrections.find(c=>c.itemId==='pending');invalid.correctionChecks=[{correctionId:c.correctionId,...speakingCorrectionSnapshot(c),writtenStatus:'correct',oralTransfer:'not_tested',reason:'fake'}];`);
await rejects('Malformed legacy arrays rejected before any saves',`invalid.targetsToReview='not-an-array';`);
await test('Needs revision and oral practice preserve source lesson in Review',()=>{run(`let retry=makeSpeakingReport();retry.speakingSessionId='test-speaking-2';retry.correctionChecks[0].writtenStatus='needs_revision';retry.correctionChecks[0].suggestedCorrection='A better version.';retry.correctionChecks[0].oralTransfer='needs_practice';saveSpeakingReport(retry);`);assert(json('buildReviewQueue()').some(x=>x.lessonId==='A'&&x.target==='spouse'&&x.reasons.includes('speaking_review')))});
await test('Older-course check links review signal to its source course',()=>{run(`const oldContext=speakingHandoffData('A').olderReviewCorrections[0];saveSpeakingReport({type:'SPEAKING_REPORT',speakingSessionId:'test-other-lesson',lessonId:'A',correctionChecks:[{correctionId:oldContext.correctionId,...speakingCorrectionSnapshot(oldContext),writtenStatus:'needs_revision',suggestedCorrection:'A better answer.',oralTransfer:'not_tested',reason:'Needs a verb.'}]})`);const sig=json('JSON.parse(localStorage.getItem("english_os_learning_signals"))');assert(sig.some(x=>x.speakingReportKey==='test-other-lesson'&&x.lessonId==='B'&&x.sessionId==='B1'))});
await test('Old Speaking report schema remains compatible',()=>{run(`saveSpeakingReport({type:'SPEAKING_REPORT',lessonId:'A',targetsToReview:['sibling'],grammarToReview:['be verbs'],betterExpressions:[{original:'x',better:'y',reason:'z'}]})`);assert(!json('buildReviewQueue()').some(x=>x.target==='sibling'));assert(!json('buildReviewQueue()').some(x=>x.target==='be verbs'));assert.deepEqual(json('JSON.parse(localStorage.getItem("english_os_speaking_reports")).at(-1).targetsToReview'),['sibling'])});
await test('Prose plus one Speaking JSON block parses and imports',()=>{const r=run('makeSpeakingReport()');r.speakingSessionId='prose-report';sandbox.prose='這次的說明\n```json\n'+JSON.stringify(r)+'\n```';assert(run('importSpeakingReportText(prose)'));assert(nodes.get('speakingChecks').innerHTML.includes('最近一次口說回報'))});
await test('Output escapes feedback HTML in results',()=>{run(`const escaped=makeSpeakingReport();escaped.speakingSessionId='html-report';escaped.correctionChecks[0].reason='<img src=x onerror=alert(1)>';saveSpeakingReport(escaped);renderSpeakingChecks()`);assert(!nodes.get('speakingChecks').innerHTML.includes('<img'));assert(nodes.get('speakingChecks').innerHTML.includes('&lt;img'))});
const {createSpeakingService}=await import('../src/speaking-service.mjs');
const db=new Map();let counter=0,cloud={},offline=false;
const service=createSpeakingService({source:async()=>structuredClone(cloud),get:async id=>structuredClone(db.get(id)||null),latest:async id=>structuredClone([...db.values()].filter(x=>x.lesson_id===id).at(-1)||null),save:async(s,r)=>{const row=db.get(s.speakingSessionId);if(r===null?!!row:row?.revision!==r)return false;db.set(s.speakingSessionId,{lesson_id:s.lessonId,state:structuredClone(s),revision:(r||0)+1});return true}},()=>String(++counter));
sandbox.fetch=async(url,options={})=>{
 if(url.includes('/functions/v1/speaking-queue')){if(offline)throw new Error('offline');try{return {ok:true,json:async()=>await service(JSON.parse(options.body))}}catch(e){return {ok:false,json:async()=>({error:e.message})}}}
 if(options.method==='POST')cloud=JSON.parse(options.body).state;
 return {ok:true,json:async()=>[]};
};
run(`localStorage.setItem('english_os_gpt_reports',JSON.stringify([reportA,reportB]));localStorage.setItem('english_os_speaking_reports','[]');localStorage.setItem('english_os_learning_signals','[]');$('speakingLesson').value='A';`);
await test('UI prepares 8-item Vocabulary/Grammar queue and keeps corrections as context',async()=>{await run('$("buildSpeakingBrief").onclick()');const b=nodes.get('speakingBrief').value;assert(b.includes('TOTAL REQUIRED COVERAGE: 8'));assert(b.indexOf('CURRENT REQUIRED ITEM')<b.indexOf('SPEAKING LOOP'));assert(b.indexOf('REMAINING QUEUE')<b.indexOf('REPORT SCHEMA'));assert(!nodes.has('correctionBrief'));assert(nodes.has('gptCheckBrief'));assert(nodes.get('speakingQueuePanel').innerHTML.includes('Coverage: 0 / 8'));assert(nodes.get('speakingQueuePanel').innerHTML.includes('Vocabulary'));assert(nodes.get('speakingQueuePanel').innerHTML.includes('Grammar'));assert(!json('speakingQueueCache.A.queue').some(x=>x.kind==='correction'));assert(b.includes(' I hope your name in spouse. '));assert(!b.includes('FAKE GPT ORIGINAL'));assert(b.includes('Praise must never replace'));assert(b.includes('Okay/Yeah'));assert(b.includes('Take your time'))});
await test('A: Normal Voice start immediately asks a lesson question',()=>{const b=nodes.get('speakingBrief').value;assert(b.includes('On the first Voice turn, immediately ask'));assert(b.includes('CURRENT REQUIRED ITEM'));assert(b.includes('The next Coach turn must contain an actual lesson question.'))});
await test('B: Yes triggers the first lesson question',()=>{const b=nodes.get('speakingBrief').value;assert(b.includes('Yes, Yeah, Yep, Okay, Sure, Ready'));assert(b.includes('Immediately ask the first lesson-linked question.'))});
await test('C: Okay triggers the first lesson question before any task',()=>{const b=nodes.get('speakingBrief').value;assert(b.includes('Before the first real Speaking question'));assert(b.includes('Okay'))});
await test('D: Question? requests an immediate question',()=>{const b=nodes.get('speakingBrief').value;assert(b.includes('Question?'));assert(b.includes("What's the question?"))});
await test('E: Learner never selects the topic or scenario',()=>{const b=nodes.get('speakingBrief').value;assert(b.includes('Do NOT ask what the learner would like to practice'));assert(b.includes('The learner does not manage the syllabus.'))});
await test('I: Repeated readiness loop is explicitly prohibited',()=>{const b=nodes.get('speakingBrief').value;assert(b.includes('HARD RULE — NO READINESS LOOP'));assert(b.includes("I'm ready whenever you are"));assert(b.includes("Let me know when you're ready"))});
await test('Text and Voice states have distinct transitions',()=>{const b=nodes.get('speakingBrief').value;assert(b.includes('BRIEF_LOADED → TEXT_READY → VOICE_ENTERED → SESSION_ACTIVE → FIRST_QUESTION_ASKED → SPEAKING_LOOP'));assert(b.includes('TEXT MODE:'));assert(b.includes('VOICE MODE:'));assert(b.includes('不要')===false||b.includes('Never repeat the text-mode message'))});
await test('Late status response cannot erase a newly prepared queue',async()=>{const realFetch=sandbox.fetch;let resolveStatus;let hold=true;sandbox.fetch=async(url,opts={})=>{if(hold&&url.includes('/functions/v1/speaking-queue')&&JSON.parse(opts.body).action==='status'){hold=false;return new Promise(resolve=>{resolveStatus=resolve})}return realFetch(url,opts)};const pending=run('refreshSpeakingQueue()');await run('prepareSpeakingQueue()');resolveStatus({ok:true,json:async()=>({state:null})});await pending;assert.equal(json('speakingQueueCache.A').sessionCoverage.total,8);sandbox.fetch=realFetch});
await test('Repeated prepare/copy reuses same attempt',async()=>{const a=json('speakingQueueCache.A');await run('$("copySpeakingBrief").onclick()');assert.equal(json('speakingQueueCache.A').activeAttempt.id,a.activeAttempt.id);assert(clipboard.includes(a.speakingSessionId))});
const s=json('speakingQueueCache.A');
function queueReport(count=2){return {type:'SPEAKING_REPORT',schemaVersion:'2.25.1',speakingSessionId:s.speakingSessionId,continuationAttemptId:s.activeAttempt.id,lessonId:'A',completed:true,endReason:'completed',speakingMinutes:25,timeBasis:'measured',phaseProgress:['warmup','lesson_application','knowledge_integration','final_challenge'].map((phaseId,i)=>({phaseId,status:i===0?'completed':i===1?'partial':'not_started',notes:i<2?'實際練習':' '})),coverageChecks:s.queue.slice(0,count).map((x,i)=>({coverageId:x.coverageId,sourceVersion:x.sourceVersion,taskMode:x.taskMode,phaseId:'lesson_application',sequence:i+1,status:'practiced',newPrompt:'Please make a new sentence.',learnerUtterance:'My '+x.target+' likes music.',utteranceReliability:'confirmed',transcriptionIssue:false,learnerFinished:true,modelOnly:false,coachSuppliedAnswer:false,productionQuality:'needs_review',newContext:true})),speakingCorrections:[{target:'spouse',coverageId:s.queue[0].coverageId,original:'My spouse like music.',better:'My spouse likes music.',reason:'Use third-person singular likes.',learnerRetried:true,retryUtterance:'My spouse likes music.'}],correctionChecks:[],overallNotes:['實際練習兩項。']}}
sandbox.uiRaw=JSON.stringify(queueReport());
await test('False GPT complete imports partial Coverage and shows spontaneous correction',async()=>{nodes.get('speakingReport').value=sandbox.uiRaw;const r=await run('$("importSpeakingReport").onclick()');assert.equal(r.osVerifiedCompleted,false);assert.equal(r.gptClaimedCompleted,true);assert(nodes.get('speakingImportResult').textContent.includes('2 / 8'));assert(nodes.get('speakingChecks').innerHTML.includes('English OS 驗證：未完成'));assert(nodes.get('speakingQueuePanel').innerHTML.includes('Coverage: 2 / 8'));assert(nodes.get('speakingChecks').innerHTML.includes('My spouse likes music.'))});
await test('Continuation button preserves 2 completed and resumes only 6 Vocabulary/Grammar items',async()=>{await run('$("resumeSpeakingQueue").onclick()');const next=json('speakingQueueCache.A');assert.equal(next.speakingSessionId,s.speakingSessionId);assert.notEqual(next.activeAttempt.id,s.activeAttempt.id);assert.equal(next.remainingCoverage.length,6);assert(!next.remainingCoverage.some(x=>x.kind==='correction'));assert(nodes.get('speakingBrief').value.includes('SPEAKING CONTINUATION'));assert(nodes.get('speakingBrief').value.includes('Do NOT restart warm-up'));assert(nodes.get('speakingBrief').value.includes('CURRENT SESSION COMPLETED: 2'));assert(nodes.get('speakingBrief').value.includes('REMAINING: 6'))});
await test('Clearing local queue cache restores server progress, no duplicate report/time',async()=>{run('speakingQueueCache={};speakingBriefDraft=null');await run('refreshSpeakingQueue()');assert.equal(json('speakingQueueCache.A').completedCoverage.length,2);assert.equal(json('JSON.parse(localStorage.getItem("english_os_speaking_reports"))').filter(x=>x.schemaVersion==='2.25.1').length,1)});
await test('Offline import preserves pending text, never grants completion or erases valid evidence',async()=>{offline=true;const before=json('speakingQueueCache.A');const raw=queueReport();raw.continuationAttemptId=before.activeAttempt.id;sandbox.offlineRaw=JSON.stringify(raw);const r=await run('importSpeakingReportText(offlineRaw)');assert.equal(r,null);assert.equal(run('localStorage.getItem("hanne_speaking_pending_report_v224")'),sandbox.offlineRaw);assert.equal(json('speakingQueueCache.A').completedCoverage.length,2);offline=false});
await test('Calling legacy saver directly cannot bypass new server gate',()=>{assert.throws(()=>run('saveSpeakingReport(JSON.parse(uiRaw))'),/伺服器/)});
await test('V2.23 parser remains compatible and cannot claim completion with missing coverage',()=>{const raw={type:'SPEAKING_REPORT',schemaVersion:'2.23.0',speakingSessionId:'legacy-223-test',lessonId:'A',completed:false,endReason:'learner_requested_stop',speakingMinutes:null,timeBasis:'not_recorded',phaseProgress:['warmup','lesson_application','knowledge_integration','final_challenge'].map(phaseId=>({phaseId,status:'not_started',notes:''})),finalChallenge:{learnerFinished:false,independentProduction:false,coachSuppliedAnswer:false,feedbackGiven:false},coverageChecks:[],correctionChecks:[],targetsUsedWell:[],targetsToReview:[],grammarToReview:[],pronunciationNotes:[],betterExpressions:[],overallNotes:[]};sandbox.legacy223=raw;assert.equal(run('saveSpeakingReport(legacy223)').schemaVersion,'2.23.0');raw.speakingSessionId='legacy-false';raw.completed=true;raw.endReason='completed';assert.throws(()=>run('saveSpeakingReport(legacy223)'))});
await test('All source answers, correction feedback, corrected_needs_review and Learning timer state preserved',()=>{assert.equal(run('localStorage.getItem("english_os_gpt_reports")'),run('JSON.stringify([reportA,reportB])'));assert.equal(json('speakingCorrectionRecords().find(c=>c.itemId==="sentence"&&c.lessonId==="A")').correctionStatus,'corrected_needs_review');assert.equal(json('sessionAnswerRecords(sessionA).find(x=>x.target==="missing")').status,'question_not_displayed');assert(!json('buildReviewQueue()').some(x=>x.target==='missing'))});
console.log(results.join('\n'));console.log('ALL PASS: '+passed);
}catch(e){console.error(results.join('\n'));console.error(e);process.exitCode=1}});
