import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
let html=fs.readFileSync(path.join(root,'index.html'),'utf8');
for(const name of ['speaking-queue.js','speaking-client.js']){
  const start='// BEGIN GENERATED '+name, end='// END GENERATED '+name;
  const a=html.indexOf(start),b=html.indexOf(end,a);
  if(a<0||b<0)throw new Error('Missing generated markers: '+name);
  html=html.slice(0,a)+start+'\n'+fs.readFileSync(path.join(root,'src',name),'utf8')+'\n'+html.slice(b);
}
const app=html.match(/<script>([\s\S]*?)<\/script>/)[1];
new vm.Script(app,{filename:'index.html inline script'});
function fn(name){const start=app.indexOf('function '+name+'('),line=app.slice(start,app.indexOf('\n',start));if(start<0)throw new Error(name);const end=line.endsWith('}')?start+line.length:app.indexOf('\n}',start)+2;return app.slice(start,end)}
const names=['getLesson','sessionById','isTopicAnswer','roundFor','flatAnswerId','sessionAnswerRecords','isAssessable','resolveGradedSource','feedbackText','teachingFields','correctionData','correctionItems','speakingCorrectionSnapshot','speakingCorrectionRecords','speakingHasReliableOralEvidence'];
const adapter='// Generated by scripts/build.mjs from existing source mapping. Do not edit independently.\nexport function sourceContext(snapshot,lessonId){\nconst localStorage={getItem:k=>snapshot[k]??null};const learnSession=null;\n'+names.map(fn).join('\n')+'\nconst lesson=getLesson(lessonId);if(!lesson)throw new Error("找不到已同步的教材。");return {lesson,corrections:speakingCorrectionRecords()};\n}\n';
fs.writeFileSync(path.join(root,'src/source-context.mjs'),adapter);
fs.writeFileSync(path.join(root,'index.html'),html);
fs.mkdirSync(path.join(root,'supabase/functions/speaking-queue'),{recursive:true});
for(const name of ['speaking-queue.js','source-context.mjs','speaking-service.mjs'])fs.copyFileSync(path.join(root,'src',name),path.join(root,'supabase/functions/speaking-queue',name));
fs.mkdirSync(path.join(root,'public'),{recursive:true});
fs.writeFileSync(path.join(root,'public/index.html'),html);
console.log('Build and inline JavaScript syntax check passed. Shared server modules synchronized.');
