// Generated by scripts/build.mjs from existing source mapping. Do not edit independently.
export function sourceContext(snapshot,lessonId){
const localStorage={getItem:k=>snapshot[k]??null};const learnSession=null;
function getLesson(id){
 let lessons=JSON.parse(localStorage.getItem("english_os_lessons")||"[]");
 return lessons.find(x=>x.id===id)||null;
}
function sessionById(id){
 if(learnSession?.id===id)return learnSession;
 return JSON.parse(localStorage.getItem("english_os_sessions")||"[]").find(s=>s.id===id)||null;
}
function isTopicAnswer(a){return ["vocab_topic_meaning","vocab_topic_spelling"].includes(a.kind)}
function roundFor(a){return a.round||a.vocabRound||(a.kind==="vocab_topic_meaning"||a.id?.startsWith("v_mean_")?"meaning":a.kind==="vocab_topic_spelling"||a.id?.startsWith("v_spell_")?"spelling":a.component==="Vocabulary"?"production":null)}
function flatAnswerId(parentId,term){return parentId+"::"+encodeURIComponent(term)}
function sessionAnswerRecords(session){
 if(!session)return [];
 const curriculum=getLesson(session.lessonId)?.curriculum||{};
 const vocabulary=[...(curriculum.mainVocabulary||[]),...(curriculum.extendedVocabulary||[]),...(curriculum.unclassifiedVocabulary||[])];
 return (session.answers||[]).flatMap(a=>{
  if(!isTopicAnswer(a)){
   const rawAnswer=String(a.userAnswer??a.originalAnswer??"");
   const status=a.status||((session.skips||[]).find(s=>s.itemId===a.id)?.reason)||(a.skipped?"not_now":rawAnswer.trim()?"answered":"unanswered");
   return [{...a,round:roundFor(a),prompt:a.prompt||a.question||a.target||"",originalAnswer:String(a.userAnswer??a.originalAnswer??""),userAnswer:String(a.userAnswer??a.originalAnswer??""),status}];
  }
  const isMeaning=a.kind==="vocab_topic_meaning",round=isMeaning?"meaning":"spelling";
  // New sessions retain the displayed prompt. Legacy sessions use row keys, never row position.
  const snapshots=Array.isArray(a.vocabSnapshot)?a.vocabSnapshot:[];
  const terms=[...new Set([...snapshots.map(v=>v.term),...Object.keys(a.rows||{})])];
  return terms.map(term=>{
   const row=a.rows?.[term]||{},v=snapshots.find(v=>v.term===term)||vocabulary.find(v=>v.term===term)||{};
   const raw=isMeaning?row.meaningAnswer:row.spellingAnswer;
   const answer=String(raw??"");
   const prompt=typeof row.prompt==="string"?row.prompt:(isMeaning?term:String(v.meaning||""));
   const missing=!!(isMeaning?row.meaningPromptMissing:row.spellingPromptMissing)||(!isMeaning&&!prompt.trim());
   const forgot=!!(isMeaning?row.meaningForgot:row.spellingForgot);
   const status=missing?"question_not_displayed":forgot?"forgot":answer.trim()?"answered":"unanswered";
   const referenceAnswer=isMeaning?String(row.referenceAnswer??v.meaning??""):term;
   return {id:flatAnswerId(a.id,term),parentId:a.id,component:"Vocabulary",kind:isMeaning?"vocab_meaning":"vocab_spelling",round,target:term,prompt,question:prompt,
    originalAnswer:answer,userAnswer:answer,status,referenceAnswer,needsGPT:true,
    promptSource:typeof row.prompt==="string"||snapshots.length?"session_snapshot":"legacy_curriculum",
    ...(isMeaning||status!=="answered"?{}:{autoCorrect:answer.toLowerCase().trim()===term.toLowerCase().trim(),correctAnswer:term})};
  });
 });
}
function isAssessable(a){return a&&["answered","forgot"].includes(a.status)&&!!a.target&&!!a.prompt}
function resolveGradedSource(g,session){
 const all=sessionAnswerRecords(session);
 let found=all.find(a=>a.id===g.id);if(found)return found;
 // Legacy page IDs may be resolved only when GPT explicitly named a unique word.
 let candidates=all.filter(a=>a.target===g.target&&(!g.component||a.component===g.component));
 if(g.id)candidates=candidates.filter(a=>a.parentId===g.id);
 if(g.round)candidates=candidates.filter(a=>a.round===g.round);
 return candidates.length===1?candidates[0]:null;
}
function feedbackText(v){return typeof v==="string"?v: Array.isArray(v)?v.filter(x=>typeof x==="string").join("\n"):""}
function teachingFields(g){
 const t=g.teachingFeedback&&typeof g.teachingFeedback==="object"?g.teachingFeedback:{};
 const get=k=>feedbackText(g[k]??t[k]);
 let examples=g.similarExamples??t.similarExamples??[];
 if(typeof examples==="string")examples=[examples];
 return {whatWasRight:get("whatWasRight"),issue:get("issue")||get("whatWasWrong"),better:get("better"),reason:get("reason"),ruleOrPattern:get("ruleOrPattern"),
  similarExamples:(Array.isArray(examples)?examples:[]).slice(0,2).map(e=>typeof e==="string"?{english:e,chinese:""}:{english:feedbackText(e?.english??e?.en??e?.sentence),chinese:feedbackText(e?.chinese??e?.zh??e?.translation)}).filter(e=>e.english)};
}
function correctionData(){
 const reports=JSON.parse(localStorage.getItem("english_os_gpt_reports")||"[]"),items=[],issues=[];
 reports.forEach((report,ri)=>{
  const session=sessionById(report.sessionId);
  (report.gradedAnswers||[]).forEach((g,ii)=>{
   const source=resolveGradedSource(g,session);
   if(!source){issues.push({ri,ii,sessionId:report.sessionId,target:g.target||"未提供",message:session?"舊報告未指明實際單字，請用原 Session 逐字重新批改。":"找不到原 Session 作答紀錄，無法確認題目與原答案；保留資料等待補回。"});return}
   if(!isAssessable(source)||g.status==="correct")return;
   if(!["developing","incorrect"].includes(g.status)){issues.push({ri,ii,sessionId:report.sessionId,target:source.target,message:"舊報告沒有可辨識的批改狀態，請重新批改。"});return}
   const teaching=teachingFields(g);
   items.push({...teaching,ri,ii,sessionId:report.sessionId,lessonId:session.lessonId,lessonTitle:session.lessonTitle,id:source.id,target:source.target,component:source.component,
    round:source.round,prompt:source.prompt,promptSource:source.promptSource,original:source.originalAnswer,answerStatus:source.status,intendedChinese:source.intendedChinese||"",better:teaching.better||source.referenceAnswer||"",
    corrected:!!g.corrected,correctionAnswer:feedbackText(g.correctionAnswer),key:report.sessionId+"::"+source.id});
  });
 });
 return {items,issues};
}
function correctionItems(){return correctionData().items}
function speakingCorrectionSnapshot(x){
 return {originalAnswer:x.originalAnswer,gptSuggestedAnswer:x.gptSuggestedAnswer,learnerCorrection:x.learnerCorrection};
}
function speakingCorrectionRecords(){
 const reports=JSON.parse(localStorage.getItem("english_os_gpt_reports")||"[]");
 const unique=new Map(),latestReports=new Map();
 reports.forEach((r,i)=>{const prev=latestReports.get(r.sessionId);if(prev===undefined||String(r.importedAt||"")>=String(reports[prev].importedAt||""))latestReports.set(r.sessionId,i)});
 correctionItems().forEach(x=>{
  if(latestReports.get(x.sessionId)!==x.ri)return;
  const report=reports[x.ri],grade=report?.gradedAnswers?.[x.ii];
  if(!grade)return;
  const corrected=!!x.corrected&&!!x.correctionAnswer.trim();
  const item={correctionId:JSON.stringify([x.sessionId,x.id]),sessionId:x.sessionId,itemId:x.id,
   lessonId:x.lessonId,lessonTitle:x.lessonTitle,component:x.component,round:x.round,target:x.target,
   prompt:x.prompt,promptSource:x.promptSource||"session_snapshot",answerStatus:x.answerStatus,
   intendedChinese:x.intendedChinese,originalAnswer:x.original,gptSuggestedAnswer:x.better,
   teachingFeedback:{whatWasRight:x.whatWasRight,issue:x.issue,reason:x.reason,ruleOrPattern:x.ruleOrPattern,similarExamples:x.similarExamples},
   learnerCorrection:corrected?x.correctionAnswer:null,
   correctionStatus:corrected?"corrected_needs_review":"not_corrected",
   correctedAt:corrected?(grade.correctedAt||null):null,
   sourceReportAt:report.importedAt||sessionById(x.sessionId)?.endedAt||""};
  const previous=unique.get(item.correctionId);
  if(!previous||item.sourceReportAt>=previous.sourceReportAt)unique.set(item.correctionId,item);
 });
 const speakingReports=JSON.parse(localStorage.getItem("english_os_speaking_reports")||"[]").slice().sort((a,b)=>String(a.importedAt||"").localeCompare(String(b.importedAt||"")));
 return [...unique.values()].map(item=>{
  const matching=speakingReports.flatMap(report=>(report.correctionChecks||[]).filter(check=>check.correctionId===item.correctionId&&JSON.stringify(check.contextSnapshot)===JSON.stringify(speakingCorrectionSnapshot(item))).map(check=>({...check,checkedAt:report.importedAt})));
  const written=matching.filter(c=>c.writtenStatus!=="not_checked").pop();
  const oral=matching.filter(speakingHasReliableOralEvidence).pop();
  const unverified=matching.filter(c=>!speakingHasReliableOralEvidence(c)&&(c.oralTransfer!=="not_tested"||c.utteranceReliability==="uncertain"||c.transcriptionIssue)).pop();
  return {...item,writtenValidationStatus:written?.writtenStatus||"not_checked",
   oralValidationStatus:oral?.oralTransfer||"not_tested",
   previousSpeakingAssessment:{written:written?{status:written.writtenStatus,reason:written.reason,suggestedCorrection:written.suggestedCorrection,checkedAt:written.checkedAt}:null,
    oral:oral?{status:oral.oralTransfer,newPrompt:oral.newPrompt,learnerUtterance:oral.learnerUtterance,utteranceReliability:oral.utteranceReliability,transcriptionIssue:oral.transcriptionIssue,reason:oral.reason,checkedAt:oral.checkedAt}:null,
    unverifiedOral:unverified?{status:"needs_recheck",reportedOutcome:unverified.oralTransfer,utteranceReliability:unverified.utteranceReliability||"not_recorded",transcriptionIssue:unverified.transcriptionIssue??null,reason:unverified.reason,checkedAt:unverified.checkedAt}:null}};
 }).sort((a,b)=>String(b.correctedAt||b.sourceReportAt).localeCompare(String(a.correctedAt||a.sourceReportAt)));
}
function speakingHasReliableOralEvidence(check){
 return ["passed","needs_practice"].includes(check.oralTransfer)&&["confirmed","likely"].includes(check.utteranceReliability)&&
  typeof check.newPrompt==="string"&&!!check.newPrompt.trim()&&typeof check.learnerUtterance==="string"&&!!check.learnerUtterance.trim();
}
const lesson=getLesson(lessonId);if(!lesson)throw new Error("找不到已同步的教材。");return {lesson,corrections:speakingCorrectionRecords()};
}
